otavanopisto/pyramus

rest/src/main/java/fi/pyramus/rest/ObjectFactory.java
=>  - Removed @Stateful from ObjectFactory

pyramus/updates/37.001/151116_unique_username.xml
=>  - Added unique constraint for InternalAuth.username

pyramus/src/main/webapp/templates/students/editstudent.jsp
=>  - Added extensionhook for editstudent header

pyramus/src/main/java/fi/pyramus/json/users/PoseJSONRequestController.java, pyramus/src/main/resources/fi/pyramus/I18N/pyramuslocale.properties, pyramus/src/main/resources/fi/pyramus/I18N/pyramuslocale_fi_FI.properties, pyramus/src/main/resources/jsonmapping.properties, pyramus/src/main/webapp/templates/students/viewstudent.jsp, pyramus/src/main/webapp/templates/users/edituser.jsp
=> Ftr 219 represent user

.travis.yml, pyramus/pom.xml, pyramus/src/test/java/fi/pyramus/rest/PersonTestsIT.java, pyramus/src/test/resources/rest-data.sql, rest/src/main/java/fi/pyramus/rest/PersonRESTService.java, rest/src/main/java/fi/pyramus/rest/StudentRESTService.java, rest/src/main/java/fi/pyramus/rest/controller/PersonController.java, rest/src/main/java/fi/pyramus/rest/controller/SchoolController.java
=> Ftr 224 persons limits

pyramus/src/test/java/fi/pyramus/rest/StaffMemberAddressTestsIT.java, rest/src/main/java/fi/pyramus/rest/StaffRESTService.java, rest/src/main/java/fi/pyramus/rest/controller/UserController.java, rest/src/main/java/fi/pyramus/rest/controller/permissions/UserPermissions.java
=> ** Added support for creating, updating, listing, finding and deleting

pyramus/src/test/java/fi/pyramus/rest/StaffMemberAddressTestsIT.java, pyramus/src/test/java/fi/pyramus/rest/StaffMemberPhoneNumberTestsIT.java, rest/src/main/java/fi/pyramus/rest/StaffRESTService.java, rest/src/main/java/fi/pyramus/rest/controller/UserController.java, rest/src/main/java/fi/pyramus/rest/controller/permissions/UserPermissions.java
=> Ftr 229 staff numbers

rest/src/main/java/fi/pyramus/rest/StudentRESTService.java
=> ** Fixed issue #232

persistence/src/main/java/fi/pyramus/dao/SystemDAO.java
=>  - Changed visibility of getEntityManager() to public

googleoauth-plugin/src/main/java/fi/pyramus/plugin/googleoauth/GoogleOauthAuthorizationStrategy.java, plugin-core/src/main/java/fi/pyramus/plugin/auth/AuthenticationProvider.java, pyramus/src/main/java/fi/pyramus/json/users/LoginJSONRequestController.java, pyramus/src/main/java/fi/pyramus/plugin/auth/internal/InternalAuthenticationStrategy.java, pyramus/src/main/java/fi/pyramus/views/users/ExternalLoginLoginViewController.java, pyramus/src/main/java/fi/pyramus/views/users/LogoutViewController.java, testauth-plugin/src/main/java/fi/pyramus/plugin/testauth/TestAuthorizationStrategy.java
=> ** Implemented feature #250

persistence/src/main/java/fi/pyramus/domainmodel/base/Person.java, persistence/src/main/java/fi/pyramus/persistence/search/CollectionBridge.java
Fixes #187 
Fixes #92 
Solution fixes the most common problem i.e. searching with full email address, searching with partial email (f.ex. stuff before @) would need analyzed field in addition.
=>  - Added Indexing support for Set<String> ...Emails for Person with

pyramus/src/main/java/fi/pyramus/views/students/CreateStudentViewController.java, pyramus/src/main/webapp/scripts/gui/students/createstudent.js
=>  - Fixed issue with adding rows phones table crashing

pyramus/updates/27.001/140930_coursestudentsasusers.xml
Fixes #218 
- Added removal and rebuilding of foreign keys and indices pointing at coursestudentold table after user refactoring
=> Fixed coursestudentold references

pyramus/src/main/java/fi/pyramus/views/students/EditStudentGroupViewController.java, pyramus/src/main/webapp/templates/students/editstudentgroup.jsp
=>  - Removed separate json call for studyprogrammes in editstudentgroup

pyramus/pom.xml, pyramus/src/test/java/fi/pyramus/rest/CourseEducationTypeTestsIT.java, pyramus/src/test/resources/rest-data.sql, rest-model/src/main/java/fi/pyramus/rest/model/CourseEducationSubtype.java, rest-model/src/main/java/fi/pyramus/rest/model/CourseEducationType.java, rest/src/main/java/fi/pyramus/rest/CourseRESTService.java, rest/src/main/java/fi/pyramus/rest/ObjectFactory.java, rest/src/main/java/fi/pyramus/rest/controller/CourseController.java, rest/src/main/java/fi/pyramus/rest/controller/permissions/CoursePermissions.java
=> Ftr 262 expose courseeducationtype in rest

googleoauth-plugin/src/main/java/fi/pyramus/plugin/googleoauth/GoogleOauthAuthorizationStrategy.java
=> ** Fixed issue #252

muikku-plugin/.gitignore, muikku-plugin/pom.xml, muikku-plugin/src/main/java/fi/pyramus/plugin/muikku/MuikkuPluginDescriptor.java, muikku-plugin/src/main/resources/META-INF/services/fi.pyramus.plugin.PluginDescriptor, muikku-plugin/src/main/resources/fi/pyramus/plugin/muikku/muikkulogin.ftl, muikku-plugin/src/main/resources/fi/pyramus/plugin/muikku/muikkulogin_fi.ftl, muikku-plugin/src/main/resources/fi/pyramus/plugin/muikku/muikkuloginhead.ftl, plugin-core/src/main/java/fi/pyramus/plugin/CustomLoginScreenPlugin.java, plugin-core/src/main/java/fi/pyramus/plugin/PluginManager.java, pom.xml, pyramus/src/main/java/fi/pyramus/freemarker/FreemarkerServlet.java, pyramus/src/main/java/fi/pyramus/views/users/AuthorizeClientApplicationViewController.java, pyramus/src/main/java/fi/pyramus/views/users/LoginViewController.java, pyramus/src/main/webapp/templates/generic/jsonform_support.jsp
=> Ftr 264 muikku login screen

muikku-plugin/pom.xml, muikku-plugin/src/main/java/fi/pyramus/plugin/muikku/AbstractCourseBasicPageHookController.java, muikku-plugin/src/main/java/fi/pyramus/plugin/muikku/EditCourseBasicPageHookController.java, muikku-plugin/src/main/java/fi/pyramus/plugin/muikku/MuikkuPluginDescriptor.java, muikku-plugin/src/main/java/fi/pyramus/plugin/muikku/ViewCourseBasicPageHookController.java, muikku-plugin/src/main/resources/fi/pyramus/plugin/muikku/editcoursebasichook.ftl, muikku-plugin/src/main/resources/fi/pyramus/plugin/muikku/editcoursebasichook_fi.ftl, pyramus/src/main/webapp/templates/courses/editcourse.jsp, pyramus/src/main/webapp/templates/courses/viewcourse.jsp
=> ** Added link to Muikku workspace into course view and edit views

pyramus/src/main/webapp/templates/generic/header.jsp
=> ** Add generic javascript hook to header

rest-model/src/main/java/fi/pyramus/rest/model/TransferCredit.java, rest/src/main/java/fi/pyramus/rest/ObjectFactory.java, rest/src/main/java/fi/pyramus/rest/StudentRESTService.java, rest/src/main/java/fi/pyramus/rest/controller/StudentController.java, rest/src/main/java/fi/pyramus/rest/controller/permissions/StudentPermissions.java
=> ** Added support for listing student's transfer credits via REST

pyramus/src/main/java/fi/pyramus/views/system/ImportExportPermissionsViewController.java, pyramus/src/main/resources/fi/pyramus/I18N/pyramuslocale.properties, pyramus/src/main/resources/fi/pyramus/I18N/pyramuslocale_fi_FI.properties, pyramus/src/main/resources/pagemapping.properties, pyramus/src/main/webapp/templates/generic/header.jsp, pyramus/src/main/webapp/templates/system/importexportpermissions.jsp
=> Ftr 267 permission matrix sync

pyramus/src/main/java/fi/pyramus/views/settings/ViewSchoolViewController.java
=> Fix for View School page NPE crash

googleoauth-plugin/src/main/java/fi/pyramus/plugin/googleoauth/GoogleOauthAuthorizationStrategy.java, muikku-plugin/src/main/resources/fi/pyramus/plugin/muikku/muikkuloginhead.ftl, plugin-core/src/main/java/fi/pyramus/plugin/auth/AuthenticationException.java, plugin-core/src/main/java/fi/pyramus/plugin/auth/LocalUserMissingException.java, pyramus/src/main/java/fi/pyramus/json/users/LoginJSONRequestController.java, pyramus/src/main/java/fi/pyramus/views/users/ExternalLoginLoginViewController.java, pyramus/src/main/java/fi/pyramus/views/users/LoginViewController.java, pyramus/src/main/resources/fi/pyramus/I18N/javascriptlocale.properties, pyramus/src/main/resources/fi/pyramus/I18N/javascriptlocale_fi_FI.properties, pyramus/src/main/resources/fi/pyramus/I18N/pyramuslocale.properties, pyramus/src/main/resources/fi/pyramus/I18N/pyramuslocale_fi_FI.properties, pyramus/src/main/webapp/scripts/ixmessageadapter.js, pyramus/src/main/webapp/templates/generic/message_adapter_support.jsp, pyramus/src/main/webapp/templates/users/login.jsp, testauth-plugin/src/main/java/fi/pyramus/plugin/testauth/TestAuthorizationStrategy.java
=> ** Fixed issue #280

persistence/src/main/java/fi/pyramus/dao/courses/CourseStudentDAO.java, rest/src/main/java/fi/pyramus/rest/CourseRESTService.java, rest/src/main/java/fi/pyramus/rest/controller/CourseController.java
=> REST functionality for listing course students also by students' activity

muikku-plugin/src/main/resources/fi/pyramus/plugin/muikku/muikkuloginhead.ftl
=> Ftr 292 responsive muikku login

pyramus/src/main/java/fi/pyramus/views/users/LogoutViewController.java
=> ** Fixes issue #294

persistence/src/main/java/fi/pyramus/dao/grading/CourseAssessmentRequestDAO.java, rest/src/main/java/fi/pyramus/rest/CourseRESTService.java
=> REST support for listing only active students' workspace assessment requests

muikku-plugin/src/main/resources/fi/pyramus/plugin/muikku/muikkuloginhead.ftl
=> * Added meta width=device-width so mobile devices can render muikku

pyramus/src/main/webapp/scripts/gui/students/createstudent.js, pyramus/src/main/webapp/templates/students/editstudent.jsp, pyramus/src/main/webapp/templates/users/createuser.jsp, pyramus/src/main/webapp/templates/users/edituser.jsp
=> Default contact type to Add/Edit User/Student views

pyramus/src/main/webapp/WEB-INF/web.xml
=> Bug 329 freemarker path

rest/src/main/java/fi/otavanopisto/pyramus/rest/PersonRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/permissions/PersonPermissions.java
=> Added permission for finding user's username

pyramus/src/main/webapp/WEB-INF/web.xml
=> ** Fixes #331

persistence/src/main/java/fi/otavanopisto/pyramus/dao/grading/CourseAssessmentDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/grading/CreditLinkDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/grading/TransferCreditDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/grading/Credit.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/grading/CreditLink.java
=> Changes to credit archived flag handling

persistence/src/main/java/fi/otavanopisto/pyramus/dao/courses/CourseDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/courses/Course.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/courses/CreateCourseJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/courses/EditCourseJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/courses/SaveStudentDetailsJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/EditGroupContactEntryJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/EditStudentJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/util/dataimport/scripting/api/CourseAPI.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/courses/CreateCourseViewController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/courses/EditCourseViewController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/EditStudentViewController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/system/DebugDataViewController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/users/AuthorizeClientApplicationViewController.java, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale_fi_FI.properties, pyramus/src/main/webapp/templates/courses/createcourse.jsp, pyramus/src/main/webapp/templates/courses/editcourse.jsp, pyramus/src/main/webapp/templates/courses/viewcourse.jsp, pyramus/src/test/java/fi/otavanopisto/pyramus/ui/base/SystemPagesStudentPermissionsTestsBase.java, pyramus/src/test/java/fi/otavanopisto/pyramus/ui/chrome/CoursesPagesStudentPermissionsTestsIT.java, pyramus/src/test/java/fi/otavanopisto/pyramus/ui/chrome/GradingPagesStudentPermissionsTestsIT.java, pyramus/updates/39.002/160527_lodgingfee.xml, rest-model/src/main/java/fi/otavanopisto/pyramus/rest/model/Course.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/CourseRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/CourseController.java, smvcj/src/main/java/fi/internetix/smvc/controllers/RequestContext.java, webservices-plugin/src/main/java/fi/pyramus/services/CoursesService.java
=> Ftr 324 course fee

smvcj/src/main/java/fi/internetix/smvc/controllers/PageRequestContext.java
=> Switched from sendRedirect to Location -header in smvcj

rest/src/main/java/fi/otavanopisto/pyramus/rest/ObjectFactory.java
=> Added null checks into ObjectMapper course assessment mapper

framework/src/main/java/fi/otavanopisto/pyramus/framework/UserUtils.java
=> Allow study programme leaders to edit credentials of users in lower roles

persistence/src/main/java/fi/otavanopisto/pyramus/dao/courses/CourseStaffMemberDAO.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/CourseRESTService.java
=> Fixes #353

muikku-plugin/pom.xml, muikku-plugin/src/main/java/fi/otavanopisto/pyramus/plugin/muikku/AbstractCourseBasicPageHookController.java, muikku-plugin/src/main/java/fi/otavanopisto/pyramus/plugin/muikku/IndexViewController.java, muikku-plugin/src/main/java/fi/otavanopisto/pyramus/plugin/muikku/MuikkuPluginDescriptor.java, muikku-plugin/src/main/java/fi/otavanopisto/pyramus/plugin/muikku/MuikkuPluginTools.java
=> Added redirect to Muikku for students and guests into Muikku plugin

persistence/src/main/java/fi/otavanopisto/pyramus/dao/grading/ProjectAssessmentDAO.java
=> Fixed issue #357

pyramus/src/main/webapp/scripts/gui/settings/createschool.js, pyramus/src/main/webapp/scripts/gui/settings/editschool.js
=> Added contact type default value to school management views

pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/CreateStudentJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/EditStudentJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/util/dataimport/scripting/api/StudentAPI.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/StudentRESTService.java, webservices-plugin/src/main/java/fi/pyramus/services/StudentsService.java
=> Bug 360 trimnames

persistence/src/main/java/fi/otavanopisto/pyramus/dao/DAOFactory.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/base/CurriculumDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/base/Curriculum.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/settings/ArchiveCurriculumJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/settings/SaveCurriculumsJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/settings/CurriculumsViewController.java, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/javascriptlocale.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/javascriptlocale_fi_FI.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale_fi_FI.properties, pyramus/src/main/resources/jsonmapping.properties, pyramus/src/main/resources/pagemapping.properties, pyramus/src/main/webapp/scripts/gui/settings/curriculums.js, pyramus/src/main/webapp/templates/generic/header.jsp, pyramus/src/main/webapp/templates/settings/curriculums.jsp, pyramus/updates/40.001/160613_curriculum.xml
=> Ftr 362 curriculumentity

persistence/src/main/java/fi/otavanopisto/pyramus/dao/students/StudentDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/students/Student.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/CopyStudentStudyProgrammeJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/CreateStudentJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/EditStudentJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/util/dataimport/scripting/api/StudentAPI.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/CreateStudentViewController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/EditStudentViewController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/system/DebugDataViewController.java, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale_fi_FI.properties, pyramus/src/main/webapp/templates/students/createstudent.jsp, pyramus/src/main/webapp/templates/students/editstudent.jsp, pyramus/src/main/webapp/templates/students/viewstudent.jsp, pyramus/src/test/java/fi/otavanopisto/pyramus/rest/PersonTestsIT.java, pyramus/src/test/java/fi/otavanopisto/pyramus/rest/StudentPermissionsTestsIT.java, pyramus/src/test/java/fi/otavanopisto/pyramus/rest/StudentTestsIT.java, pyramus/updates/40.002/160614_studentcurriculum.xml, rest-model/src/main/java/fi/otavanopisto/pyramus/rest/model/Student.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/ObjectFactory.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/StudentRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/CurriculumController.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/StudentController.java, webservices-plugin/src/main/java/fi/pyramus/services/StudentsService.java
Fixes #364 
This is a follow-up to PR #368 which should be merged first.
=> Ftr 364 studentcurriculum

pyramus/src/test/java/fi/otavanopisto/pyramus/rest/CurriculumTestsIT.java, pyramus/src/test/resources/rest-data.sql, rest-model/src/main/java/fi/otavanopisto/pyramus/rest/model/Curriculum.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/CommonRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/ObjectFactory.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/CurriculumController.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/permissions/CommonPermissions.java
=> REST methods for Curriculum

pyramus/.gitignore, pyramus/src/test/java/fi/otavanopisto/pyramus/AbstractIntegrationTest.java, pyramus/src/test/java/fi/otavanopisto/pyramus/Common.java, pyramus/src/test/java/fi/otavanopisto/pyramus/rest/CourseStudentsPermissionsTestsIT.java, pyramus/src/test/java/fi/otavanopisto/pyramus/rest/CourseStudentsTestsIT.java, pyramus/src/test/java/fi/otavanopisto/pyramus/rest/ModuleVariablePermissionsTestsIT.java, pyramus/src/test/java/fi/otavanopisto/pyramus/rest/PersonTestsIT.java, pyramus/src/test/java/fi/otavanopisto/pyramus/rest/StaffMemberTestsIT.java, pyramus/src/test/java/fi/otavanopisto/pyramus/rest/StudentPermissionsTestsIT.java, pyramus/src/test/resources/rest-data.sql
=> Bug 371 tests

persistence/src/main/java/fi/otavanopisto/pyramus/dao/courses/CourseDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/modules/ModuleDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/base/CourseBase.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/base/Curriculum.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/courses/EditCourseJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/modules/SearchModulesJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/courses/CourseChangeModuleDialogViewController.java, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale_fi_FI.properties, pyramus/src/main/resources/pagemapping.properties, pyramus/src/main/webapp/css/theme.css, pyramus/src/main/webapp/scripts/gui/courses/searchmodulesdialog.js, pyramus/src/main/webapp/templates/courses/changemodule.jsp, pyramus/src/main/webapp/templates/courses/editcourse.jsp, rest/src/main/java/fi/otavanopisto/pyramus/rest/CommonRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/permissions/CommonPermissions.java
=> Ftr 303 course changemodule

pyramus/src/test/java/fi/otavanopisto/pyramus/rest/CourseStudentsPermissionsTestsIT.java, pyramus/src/test/java/fi/otavanopisto/pyramus/rest/CurriculumPermissionsTestsIT.java, pyramus/src/test/java/fi/otavanopisto/pyramus/rest/PersonTestsIT.java, pyramus/src/test/java/fi/otavanopisto/pyramus/rest/StudentPermissionsTestsIT.java, pyramus/src/test/java/fi/otavanopisto/pyramus/rest/StudentTestsIT.java, pyramus/src/test/resources/rest-data.sql
- Added Curriculum permissions tests
Fixes #374
=>  - Fixed and reactivated tests that broke the test suite previously

pyramus/src/main/java/fi/otavanopisto/pyramus/json/settings/ArchiveTimeUnitJSONRequestController.java, pyramus/src/main/resources/jsonmapping.properties
=> Bug 72 archivetimeunit

persistence/src/main/java/fi/otavanopisto/pyramus/persistence/search/filters/StudentIdFilterFactory.java
=>  - Fixed student search by student group

persistence/src/main/java/fi/otavanopisto/pyramus/dao/reports/ReportDAO.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/system/ImportReportViewController.java, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale_fi_FI.properties, pyramus/src/main/webapp/templates/system/importreport.jsp
Fixes #361 
Allows admins to update report categories but the separate issue of management view for reports still exist.
=>  - Added report category to import report view

pyramus/src/main/webapp/css/forms.css
=>  - Changed z-index of related actions menu as it overlapped main menu

pyramus/src/main/java/fi/otavanopisto/pyramus/views/settings/EditSchoolViewController.java
=>  - Fixed a bug where phone numbers and emails were cross referenced in

rest/src/main/java/fi/otavanopisto/pyramus/rest/SystemRESTService.java
=> Pyramus whoami REST to only return unique email addresses

persistence/src/main/java/fi/otavanopisto/pyramus/dao/grading/TransferCreditDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/grading/TransferCreditTemplateCourseDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/grading/TransferCreditTemplateDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/grading/TransferCredit.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/grading/TransferCreditTemplate.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/grading/TransferCreditTemplateCourse.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/grading/LoadTransferCreditTemplateJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/grading/SaveTransferCreditsJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/settings/CreateTransferCreditTemplateJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/settings/EditTransferCreditTemplateJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/grading/ManageTransferCreditsViewController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/settings/CreateTransferCreditTemplateViewController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/settings/EditTransferCreditTemplateViewController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/settings/ManageTransferCreditTemplatesViewController.java, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/javascriptlocale.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/javascriptlocale_fi_FI.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale_fi_FI.properties, pyramus/src/main/webapp/scripts/gui/settings/createtransfercredittemplate.js, pyramus/src/main/webapp/scripts/gui/settings/edittransfercredittemplate.js, pyramus/src/main/webapp/templates/grading/managetransfercredits.jsp, pyramus/src/main/webapp/templates/settings/createtransfercredittemplate.jsp, pyramus/src/main/webapp/templates/settings/edittransfercredittemplate.jsp, pyramus/updates/41.001/160810_transfercreditcurriculum.xml, webservices-plugin/src/main/java/fi/pyramus/services/GradingService.java
=> Ftr 384 transfercreditcurriculum

rest/src/main/java/fi/otavanopisto/pyramus/rest/StudentRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/StudentGroupController.java
=> Pagination support for listing user groups via REST

pyramus/src/main/webapp/css/theme.css
=>  - Fixed issue with search result container css classes applying too

framework/src/main/java/fi/otavanopisto/pyramus/security/impl/EnvironmentPermissionResolver.java
=> Log failed permission checks

framework/src/main/java/fi/otavanopisto/pyramus/security/impl/EnvironmentPermissionResolver.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/filter/SecurityFilter.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/security/RESTSecurity.java
=> Refactored Pyramus permission logging

persistence/src/main/java/fi/otavanopisto/pyramus/dao/courses/CourseDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/modules/ModuleDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/base/CourseBase.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/courses/CreateCourseJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/courses/EditCourseJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/modules/CreateModuleJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/modules/EditModuleJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/util/dataimport/scripting/api/CourseAPI.java, pyramus/src/main/java/fi/otavanopisto/pyramus/util/dataimport/scripting/api/ModuleAPI.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/ViewStudentViewController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/system/DebugDataViewController.java, pyramus/src/main/webapp/templates/courses/createcourse.jsp, pyramus/src/main/webapp/templates/courses/editcourse.jsp, pyramus/src/main/webapp/templates/courses/viewcourse.jsp, pyramus/src/main/webapp/templates/modules/createmodule.jsp, pyramus/src/main/webapp/templates/modules/editmodule.jsp, pyramus/src/main/webapp/templates/modules/viewmodule.jsp, pyramus/src/main/webapp/templates/students/viewstudent.jsp, pyramus/src/test/java/fi/otavanopisto/pyramus/rest/CoursePermissionsTestsIT.java, pyramus/updates/42.001/161017_multicurriculum.xml, rest-model/src/main/java/fi/otavanopisto/pyramus/rest/model/Course.java, rest-model/src/main/java/fi/otavanopisto/pyramus/rest/model/Module.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/CourseRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/ModuleRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/ObjectFactory.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/CourseController.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/ModuleController.java, webservices-plugin/src/main/java/fi/pyramus/services/CoursesService.java, webservices-plugin/src/main/java/fi/pyramus/services/ModulesService.java
=> Ftr 396 multicurriculum

pyramus/src/main/webapp/templates/students/viewstudent.jsp
=> Fixed issue with linked credits not showing in student credits

persistence/src/main/java/fi/otavanopisto/pyramus/dao/students/StudentGroupDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/students/StudentGroup.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/CreateStudentGroupJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/EditStudentGroupJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/util/dataimport/scripting/api/StudentGroupAPI.java, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale_fi_FI.properties, pyramus/src/main/webapp/templates/students/createstudentgroup.jsp, pyramus/src/main/webapp/templates/students/editstudentgroup.jsp, pyramus/src/test/java/fi/otavanopisto/pyramus/rest/StudentGroupPermissionTestsIT.java, pyramus/src/test/java/fi/otavanopisto/pyramus/rest/StudentGroupTestsIT.java, pyramus/src/test/resources/rest-data.sql, pyramus/src/test/resources/ui-data.sql, pyramus/updates/41.002/161104_guidancegroup.xml, rest-model/src/main/java/fi/otavanopisto/pyramus/rest/model/StudentGroup.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/ObjectFactory.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/StudentGroupController.java
=> Ftr 411 guidance groups

rest/src/main/java/fi/otavanopisto/pyramus/rest/StudentRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/StudentController.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/permissions/StudentPermissions.java
=> ** Fix #419

pyramus/updates/42.002/161104_guidancegroup.xml
=> Bump database update 41.002 to 42.002

pyramus/src/main/webapp/templates/students/viewstudent.jsp
=> Fixed nested for loop indexing

rest/src/main/java/fi/otavanopisto/pyramus/rest/StudentRESTService.java
=> ** Fixes #429

persistence/src/main/java/fi/otavanopisto/pyramus/dao/base/PersonDAO.java
=> Fixed searching by email by changing @ to wildcard ?

pyramus/src/main/webapp/templates/students/editstudent.jsp
=> Added more space for variable name in editstudent

persistence/src/main/java/fi/otavanopisto/pyramus/dao/users/UserVariableDAO.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/projects/ViewProjectViewController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/ViewStudentViewController.java, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale_fi_FI.properties, pyramus/src/main/webapp/templates/students/editstudent.jsp, pyramus/src/main/webapp/templates/students/viewstudent.jsp
=> Ftr 439 viewstudent variables

rest/src/main/java/fi/otavanopisto/pyramus/rest/StudentRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/AssessmentController.java
=> REST endpoints for retrieving student's latest evaluation data

persistence/src/main/java/fi/otavanopisto/pyramus/dao/grading/CourseAssessmentDAO.java, pyramus/src/main/webapp/templates/system/managepermissions.jsp, pyramus/src/test/java/fi/otavanopisto/pyramus/rest/CourseAssessmentTestsIT.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/StudentRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/AssessmentController.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/util/ISO8601Timestamp.java
=> Ftr 450 assessmentcount

rest/src/main/java/fi/otavanopisto/pyramus/rest/ObjectFactory.java
=> Added null check for null contactinfo

persistence/src/main/java/fi/otavanopisto/pyramus/dao/students/StudentGroupDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/students/StudentGroupUser.java
=> Fixed student group search by staffMember

persistence/src/main/java/fi/otavanopisto/pyramus/dao/base/SchoolDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/base/School.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/settings/CreateSchoolJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/settings/EditSchoolJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/util/dataimport/scripting/api/SchoolAPI.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/system/setupwizard/SchoolsSetupWizardViewController.java, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale_fi_FI.properties, pyramus/src/main/webapp/templates/settings/createschool.jsp, pyramus/src/main/webapp/templates/settings/editschool.jsp, pyramus/src/main/webapp/templates/settings/viewschool.jsp, pyramus/updates/44.002/170215_schoolbilling.xml, rest/src/main/java/fi/otavanopisto/pyramus/rest/SchoolRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/SchoolController.java, webservices-plugin/src/main/java/fi/pyramus/services/BaseService.java
=> Added BillingDetails to School

pyramus/src/main/webapp/templates/students/createstudentgroup.jsp, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/permissions/CommonPermissions.java
=> Bug 474 studyguider permissions

rest-model/src/main/java/fi/otavanopisto/pyramus/rest/model/CourseDescription.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/CourseRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/ObjectFactory.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/CourseController.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/permissions/CoursePermissions.java
=> REST endpoints for listing and creating course descriptions

rest/src/main/java/fi/otavanopisto/pyramus/rest/CompositeRESTService.java
=> Send student nicknames to new evaluation

persistence/src/main/java/fi/otavanopisto/pyramus/dao/courses/CourseStudentDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/courses/CourseStudent.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/courses/CreateCourseJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/courses/EditCourseJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/courses/SaveStudentDetailsJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/projects/EditStudentProjectJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/util/dataimport/scripting/api/CourseStudentAPI.java, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale_fi_FI.properties, pyramus/src/main/webapp/css/studentdetailsdialog.css, pyramus/src/main/webapp/scripts/gui/courses/editcourse.js, pyramus/src/main/webapp/templates/courses/studentdetailsdialog.jsp, pyramus/updates/45.001/170508_reservationfee.xml, rest/src/main/java/fi/otavanopisto/pyramus/rest/CourseRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/CourseController.java, webservices-plugin/src/main/java/fi/pyramus/services/CoursesService.java
=> Added reservation fee field

rest/src/main/java/fi/otavanopisto/pyramus/rest/StudentRESTService.java
=> Added listing of students' assessments as a collection

persistence/src/main/java/fi/otavanopisto/pyramus/dao/base/BillingDetailsDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/base/BillingDetails.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/courses/SaveStudentDetailsJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/settings/CreateSchoolJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/settings/EditSchoolJSONRequestController.java, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale_fi_FI.properties, pyramus/src/main/webapp/scripts/gui/courses/editcourse.js, pyramus/src/main/webapp/templates/courses/studentdetailsdialog.jsp, pyramus/updates/47.001/170622_billingoperator.xml
=> Added e-billing operator to student billing details

persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/base/Person.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/EditStudentJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/EditStudentViewController.java
* Fixed issue with searching by student groups (users.id was not indexed). 
* Hopefully fixed issue with search by studyprogramme (possibly indexed with old data). 
* Implemented sorting of studyprogrammes in editstudent
Fixes #524
Closes #525
=> Fixed issues

pyramus/src/main/webapp/templates/students/createstudentgroup.jsp
=> Fixed saving of guidanceGroup selection in create student group

pyramus/src/main/java/fi/otavanopisto/pyramus/json/users/PoseJSONRequestController.java
=> Changed posing to do so always on the default user of person

persistence/src/main/java/fi/otavanopisto/pyramus/dao/.gitignore, pyramus/src/test/java/fi/otavanopisto/pyramus/rest/StudentContactLogEntryPermissionTestsIT.java, pyramus/src/test/java/fi/otavanopisto/pyramus/rest/StudentContactURLPermissionTestsIT.java, pyramus/src/test/java/fi/otavanopisto/pyramus/rest/StudentCoursesTestsPermissionsIT.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/permissions/CommonPermissions.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/permissions/CourseAssessmentPermissions.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/permissions/CoursePermissions.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/permissions/ModulePermissions.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/permissions/PersonPermissions.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/permissions/ProjectPermissions.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/permissions/SchoolPermissions.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/permissions/StudentContactLogEntryPermissions.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/permissions/StudentGroupPermissions.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/permissions/StudentPermissions.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/permissions/UserPermissions.java
- changed access of some common find/list permissions to EVERYONE
- added study guider to most find/list permissions
- added study guider to all course assessment related permissions
- resolves #532
=> Study guider permission changes

persistence/src/main/java/fi/otavanopisto/pyramus/dao/DAOFactory.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/users/PersonVariableDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/users/PersonVariableKeyDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/users/PersonVariable.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/users/PersonVariableKey.java, pyramus/updates/50.001/170912_personvariable.xml
=> Added PersonVariable

persistence/src/main/java/fi/otavanopisto/pyramus/dao/DAOFactory.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/application/ApplicationLogDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/application/ApplicationLog.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/ArchiveLogEntryJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/ListLogEntriesJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/SaveLogEntryJSONRequestController.java, pyramus/src/main/resources/jsonmapping.properties, pyramus/src/main/webapp/css/application.css, pyramus/src/main/webapp/scripts/gui/application/application-management.js, pyramus/src/main/webapp/templates/applications/manage-log.jsp, pyramus/src/main/webapp/templates/applications/manage.jsp, pyramus/updates/51.001/170913_applicationlog.xml
=> Application notes

persistence/src/main/java/fi/otavanopisto/pyramus/dao/DAOFactory.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/application/ApplicationAttachmentDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/application/ApplicationAttachment.java, pyramus/src/main/webapp/scripts/gui/application/application.js, pyramus/updates/52.001/170918-applicationattachment.xml, rest/src/main/java/fi/otavanopisto/pyramus/rest/ApplicationRESTService.java
=> Sync application attachments between file system and database

pyramus/src/main/java/fi/otavanopisto/pyramus/util/MailAttachment.java, pyramus/src/main/java/fi/otavanopisto/pyramus/util/MailEvent.java, pyramus/src/main/java/fi/otavanopisto/pyramus/util/MailService.java, pyramus/src/main/java/fi/otavanopisto/pyramus/util/Mailer.java
=> Support for sending emails

common/src/main/java/fi/otavanopisto/pyramus/events/ApplicationCreatedEvent.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/application/ApplicationDAO.java, pyramus/src/main/java/fi/otavanopisto/pyramus/util/ApplicationMailerUtils.java, pyramus/src/main/java/fi/otavanopisto/pyramus/util/Mailer.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/applications/ApplicationUtils.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/applications/CreateApplicationViewController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/applications/ManageApplicationViewController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/applications/ViewApplicationViewController.java, pyramus/src/main/webapp/scripts/gui/application/application.js, pyramus/src/main/webapp/templates/applications/application-form.jsp, pyramus/src/main/webapp/templates/applications/mail-confirmation.html, rest/src/main/java/fi/otavanopisto/pyramus/rest/ApplicationRESTService.java
- resolves #550
- miscellaneous refactoring and bug fixes
=> Application confirmation mails

persistence/src/main/java/fi/otavanopisto/pyramus/dao/application/ApplicationDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/students/Student.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/users/User.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/SaveApplicationJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/applications/EditApplicationViewController.java, pyramus/src/main/webapp/css/application.css, pyramus/src/main/webapp/scripts/gui/application/application.js, pyramus/src/main/webapp/templates/applications/application-edit-gateway.jsp, pyramus/src/main/webapp/templates/applications/management-view-application.jsp, rest/src/main/java/fi/otavanopisto/pyramus/rest/ApplicationRESTService.java
- resolves #547 
- various minor bug fixes
=> Prevent editing of locked applications

pyramus/src/main/java/fi/otavanopisto/pyramus/views/applications/ViewApplicationViewController.java, pyramus/src/main/webapp/templates/applications/application-form.jsp
=> Previous studies as a memo

common/src/main/java/fi/otavanopisto/pyramus/events/CourseAssessmentEvent.java, common/src/main/java/fi/otavanopisto/pyramus/events/TransferCreditEvent.java, common/src/main/java/fi/otavanopisto/pyramus/events/types/Created.java, common/src/main/java/fi/otavanopisto/pyramus/events/types/Removed.java, common/src/main/java/fi/otavanopisto/pyramus/events/types/Updated.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/grading/CourseAssessmentDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/grading/TransferCreditDAO.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/courses/SaveCourseAssessmentsJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/grading/SaveCourseAssessmentJSONRequestController.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/AssessmentController.java, webservices-plugin/src/main/java/fi/pyramus/services/GradingService.java
=> Added events to transfercredits and courseassessments

pyramus/src/main/webapp/css/application.css, pyramus/src/main/webapp/scripts/gui/application/application.js, pyramus/src/main/webapp/templates/applications/application-form.jsp
=> Applications: Select nickname from entered first names

smvcj/src/main/java/fi/internetix/smvc/controllers/BinaryRequestContext.java
=> Fix for Chrome content disposition error with student files

common/src/main/java/fi/otavanopisto/pyramus/events/ApplicationModifiedByApplicantEvent.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/application/ApplicationDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/application/ApplicationNotificationDAO.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/SendMailJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/UpdateApplicationStateJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/util/ApplicationMailerUtils.java, pyramus/src/main/java/fi/otavanopisto/pyramus/util/MailEvent.java, pyramus/src/main/java/fi/otavanopisto/pyramus/util/MailService.java, pyramus/src/main/java/fi/otavanopisto/pyramus/util/Mailer.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/applications/ApplicationUtils.java
- resolves #605 
- resolves #580
=> Application state change emails

pyramus/src/main/webapp/scripts/gui/applications/application.js, pyramus/src/main/webapp/templates/applications/application-form.jsp
- resolves #544
- minor application form field fix for mk
=> SSN validation

rest/src/main/java/fi/otavanopisto/pyramus/rest/CompositeRESTService.java
- requires Muikku 3470
- resolves #609
=> Study guider students only in evaluation

pyramus/src/main/java/fi/otavanopisto/pyramus/views/system/setupwizard/CourseStatesSetupWizardViewController.java, pyramus/src/main/webapp/scripts/gui/system/setupwizard/coursestates.js, pyramus/updates/49.001/170821_applications.xml
Fix Bug #616 applications database update file crushes
=> Fix Bug #616 applications database update file crushes

pyramus/src/main/java/fi/otavanopisto/pyramus/views/system/setupwizard/CourseParticipationTypesSetupWizardViewController.java, pyramus/src/main/webapp/scripts/gui/system/setupwizard/courseparticipationtypes.js
Fix Bug #614 setup wizard crashes if no default course state or multiple course participation states set
=> Fixes #614 Setup wizard crashes participation states

framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiAikuistenPerusopetuksenStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiClient.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiLukioStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiStudentHandler.java
=> 633 skip unresolvable credits

framework/src/main/java/fi/otavanopisto/pyramus/koski/model/aikuistenperusopetus/AikuistenPerusopetuksenKurssinTunniste.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/lukio/LukionOpiskeluoikeudenLisatiedot.java
Closes #626 
Also ignores laajuus if it is null.
=> Removed empty lists from additional info

framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiAikuistenPerusopetuksenStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiLukioStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/aikuistenperusopetus/AikuistenPerusopetuksenOppiaineenSuoritusAidinkieli.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/aikuistenperusopetus/AikuistenPerusopetuksenOppiaineenSuoritusMuu.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/aikuistenperusopetus/AikuistenPerusopetuksenOppiaineenSuoritusPaikallinen.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/aikuistenperusopetus/AikuistenPerusopetuksenOppiaineenSuoritusVierasKieli.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/aikuistenperusopetus/AikuistenPerusopetuksenOppiaineenTunniste.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/aikuistenperusopetus/AikuistenPerusopetuksenValtakunnallinenOppiaineenTunniste.java
Fixes #630 
Also fixes issue where religion subjects could be matched from wrong education type.
=> Removed mandatory field from local subject

framework/src/main/java/fi/otavanopisto/pyramus/koski/model/KurssinArviointi.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/KurssinArviointiNumeerinen.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/KurssinArviointiSanallinen.java
=> Fixed wrong field name

framework/src/main/java/fi/otavanopisto/pyramus/koski/model/aikuistenperusopetus/AikuistenPerusopetuksenOppiaineenSuoritus.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/apa/APAOppiaineenSuoritus.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/lukio/LukionOppiaineenSuoritus.java
=> Ignore empty assessment array

framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiAikuistenPerusopetuksenStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiLukioStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiSettings.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/apa/KoskiAPAStudentHandler.java
=> Fixes issue when study end reason is not defined

rest/src/main/java/fi/otavanopisto/pyramus/rest/ObjectFactory.java
=> Added check for null grade when passing passing

framework/src/main/java/fi/otavanopisto/pyramus/koski/CreditStub.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiClient.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiLukioStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiSettings.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/aikuistenperusopetus/AikuistenPerusopetuksenOppiaineenSuoritus.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/lukio/LukionOppiaineenArviointi.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/lukio/LukionOppiaineenSuoritus.java
* Added sorting by coursenumber (#641)
* Added skipping of students without ssn and oid (#648)
* Fixed issue with literal summary grading (#646)
Closes #641 
Closes #648 
Fixes #646
=> Sorting and summary grading

framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiAikuistenPerusopetuksenStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiLukioStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/koodisto/OpintojenRahoitus.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/OpiskeluoikeusJakso.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/apa/KoskiAPAStudentHandler.java
=> 650 rahoitus

pyramus/src/main/java/fi/otavanopisto/pyramus/util/ApplicationMailerUtils.java, pyramus/src/main/webapp/templates/applications/application-edit-gateway.jsp, pyramus/src/main/webapp/templates/applications/mail-confirmation-footer-aikuislukio.html, pyramus/src/main/webapp/templates/applications/mail-confirmation-footer-aineopiskelu.html, pyramus/src/main/webapp/templates/applications/mail-confirmation-footer-bandilinja.html, pyramus/src/main/webapp/templates/applications/mail-confirmation-footer-kasvatustieteet.html, pyramus/src/main/webapp/templates/applications/mail-confirmation-footer-mk.html, pyramus/src/main/webapp/templates/applications/mail-confirmation-footer-nettilukio.html, pyramus/src/main/webapp/templates/applications/mail-confirmation-footer-nettipk.html, pyramus/src/main/webapp/templates/applications/mail-confirmation.html
=> Line specific application contacts

framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiClient.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiEventListeners.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiSettings.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/DAOFactory.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/koski/KoskiPersonLogDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/koski/KoskiPersonState.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/EditStudentJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/ListKoskiPersonLogEntriesJSONRequestController.java, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale_fi_FI.properties, pyramus/src/main/resources/jsonmapping.properties, pyramus/src/main/webapp/css/theme.css, pyramus/src/main/webapp/scripts/gui/students/koski.js, pyramus/src/main/webapp/templates/students/editstudent.jsp, pyramus/src/main/webapp/templates/students/viewstudent.jsp
=> 652 koski status

pyramus/src/main/java/fi/otavanopisto/pyramus/views/applications/ApplicationUtils.java, pyramus/src/main/webapp/templates/applications/application-edit-gateway.jsp, pyramus/src/main/webapp/templates/applications/application-form.jsp, pyramus/src/main/webapp/templates/applications/createmailtemplate.jsp, pyramus/src/main/webapp/templates/applications/createnotification.jsp, pyramus/src/main/webapp/templates/applications/editmailtemplate.jsp, pyramus/src/main/webapp/templates/applications/editnotification.jsp, pyramus/src/main/webapp/templates/applications/mail-confirmation-footer-laakislinja.html, pyramus/src/main/webapp/templates/applications/management-browse-applications.jsp
=> Lääkislinja application form 

pyramus/src/main/webapp/scripts/gui/applications/application.js
=> Field by field validation in applications

pyramus/src/main/java/fi/otavanopisto/pyramus/views/applications/ApplicationUtils.java, pyramus/src/main/webapp/templates/applications/application-edit-gateway.jsp, pyramus/src/main/webapp/templates/applications/application-form.jsp, pyramus/src/main/webapp/templates/applications/createmailtemplate.jsp, pyramus/src/main/webapp/templates/applications/createnotification.jsp, pyramus/src/main/webapp/templates/applications/editmailtemplate.jsp, pyramus/src/main/webapp/templates/applications/editnotification.jsp, pyramus/src/main/webapp/templates/applications/mail-confirmation-footer-kasvatustieteet.html, pyramus/src/main/webapp/templates/applications/management-browse-applications.jsp
=> Application form for kasvatustieteen linja

pyramus/src/main/java/fi/otavanopisto/pyramus/views/system/ErrorReportViewController.java, pyramus/src/main/resources/pagemapping.properties, pyramus/src/main/webapp/templates/generic/errorpage.jsp, pyramus/src/main/webapp/templates/system/errorreport.jsp
Fixes #281 BUG pyramus error form
=> Bug 281 pyramus error form

pyramus/src/main/java/fi/otavanopisto/pyramus/json/users/LoginJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/users/ExternalLoginLoginViewController.java, smvcj/src/main/java/fi/internetix/smvc/AlreadyLoggedInException.java, smvcj/src/main/java/fi/internetix/smvc/InvalidLoginException.java, smvcj/src/main/java/fi/internetix/smvc/dispatcher/Servlet.java
=> Added specific types for some login exceptions

framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiAikuistenPerusopetuksenStudentHandler.java
=> Fixed subject literal assessment not handled correctly

framework/src/main/java/fi/otavanopisto/pyramus/koski/CreditStub.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/CreditStubCredit.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiAikuistenPerusopetuksenStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiLukioStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/apa/KoskiAPAStudentHandler.java
=> 686 courselink tunnustettu

persistence/src/main/java/fi/otavanopisto/pyramus/dao/students/StudentDAO.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/CourseRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/permissions/StudentPermissions.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/security/RESTSecurity.java
- resolves #689
- study guiders' students now ignore students in archived user groups
- removed some deprecated debug logging in RESTSecurity
=> Study guider restrictions for listing course students

framework/src/main/java/fi/otavanopisto/pyramus/framework/PyramusViewController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/help/ViewHelpPageViewController.java
=> Help page request parameter validation

framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiAikuistenPerusopetuksenStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiLukioStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/Suoritus.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/apa/KoskiAPAStudentHandler.java
=> Koski: todistuksellanäkyvätlisätiedot + getarvosana npe fix

framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiAikuistenPerusopetuksenStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiLukioStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/apa/KoskiAPAStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/internetix/KoskiInternetixLukioStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/internetix/KoskiInternetixPkStudentHandler.java
=> 705 linked studies

framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiAikuistenPerusopetuksenStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiLukioStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/apa/KoskiAPAStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/internetix/KoskiInternetixLukioStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/internetix/KoskiInternetixPkStudentHandler.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/koski/KoskiPersonState.java, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale_fi_FI.properties
=> Logged more Koski warnings

pyramus/src/main/webapp/scripts/gui/settings/studyendreasons.js
Fixes #601 Activate state of delete icons fails when deleting a study
=> Fixes #601 Activate state of delete icons fails when deleting a study

framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiStudentHandler.java
=> Fixed NPE when no credits is found for a single curriculum

pyramus/src/test/java/fi/otavanopisto/pyramus/rest/CourseStudentsPermissionsTestsIT.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/CourseRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/permissions/OnlyGroupStudentsPermissionFeature.java
=> Find course student permission fix for study guiders

persistence/src/main/java/fi/otavanopisto/pyramus/dao/application/ApplicationDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/application/Application.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/UpdateApplicationStateJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/applications/ApplicationUtils.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/applications/ManageApplicationViewController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/applications/ViewApplicationViewController.java, pyramus/src/main/webapp/scripts/gui/applications/application-management.js, pyramus/src/main/webapp/templates/applications/management-fragment-meta.jsp, pyramus/updates/62.001/180220_applications.xml
=> Applications: Add applicant as student

persistence/src/main/java/fi/otavanopisto/pyramus/dao/base/DefaultsDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/base/Defaults.java
Fixes #708 Setup Wizard NullPointerException
=> Fixes #708 Setup Wizard NullPointerException

pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/ListLogEntriesJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/UpdateApplicationStateJSONRequestController.java, pyramus/src/main/webapp/templates/applications/mail-credentials-create.html
- fixes #727 
- fixed NPE if log entry has no user (entry by applicant)
- set newly created student as default user for the underlying person
- tidied up credential creation mail template
=> Applications: Miscellaneous bug fixes

pyramus/src/main/webapp/templates/students/editstudent.jsp
=> Fixed issue with adding lodging periods to multiple studyprogrammes

pyramus/src/main/webapp/scripts/ixtable/ixtable.js
=> Added changevalue event when filling a column in ixtable

framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiAikuistenPerusopetuksenStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiClient.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiLukioStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/apa/KoskiAPAStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/internetix/KoskiInternetixLukioStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/internetix/KoskiInternetixPkStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/result/KoskiErrorMessageBody.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/koski/KoskiPersonLogDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/koski/KoskiPersonLog.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/ListKoskiPersonLogEntriesJSONRequestController.java, pyramus/src/main/webapp/scripts/gui/students/koski.js, pyramus/updates/64.001/180309_koskipersonlogdetails.xml
=> Details to Koski log entries

pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/ArchiveApplicationJSONRequestController.java, pyramus/src/main/resources/jsonmapping.properties, pyramus/src/main/webapp/css/application.css, pyramus/src/main/webapp/scripts/gui/applications/application-management.js, pyramus/src/main/webapp/templates/applications/management-fragment-meta.jsp
=> Applications: Archive support

framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/settings/KoskiIntegrationSettings.java
Adds a list of gradeIds to koski-config.json to skip when enumerating credits.
Closes #750
=> Added filteredGrades credit filter

persistence/src/main/java/fi/otavanopisto/pyramus/dao/grading/CourseAssessmentRequestDAO.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/StudentRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/AssessmentController.java
Fixes #755 Evaluation request's archiving
=> Fix BUG #755 Evaluation request's archiving

pyramus/src/main/webapp/templates/users/edituser.jsp
=> Added role to edituser when it cannot be edited

framework/src/main/java/fi/otavanopisto/pyramus/applications/ApplicationUtils.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/applications/CreateApplicationViewController.java, pyramus/src/main/webapp/scripts/gui/applications/application.js, pyramus/src/main/webapp/templates/applications/application-form.jsp
- resolves #772 (for Internetix applicants, ask about school after basic details)
- resolves #764 (support for predefined application line)
=> Some application issues

pyramus/src/main/webapp/templates/courses/editcourse.jsp
=> Added required to course staff member role

pyramus/src/main/webapp/templates/courses/managecourseassessments.jsp
=> Fixed validation issue when changing state of a row

framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiAikuistenPerusopetuksenStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiLukioStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/apa/KoskiAPAStudentHandler.java
=> Moved curriculum checks after archived check

persistence/src/main/java/fi/otavanopisto/pyramus/dao/application/ApplicationDAO.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/SaveApplicationJSONRequestController.java, pyramus/src/main/webapp/scripts/gui/applications/application.js, pyramus/src/main/webapp/templates/applications/application-form.jsp, rest/src/main/java/fi/otavanopisto/pyramus/rest/ApplicationRESTService.java
- resolves #765, resolves #769, resolves #774
=> Miscellaneous application features

rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/permissions/OnlyGroupStudentsPermissionFeature.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/permissions/OnlyOwnGroupsPermissionFeature.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/security/RESTCourseStudentUserContextResolverImpl.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/security/RESTUserEntityContextResolverImpl.java
=> Changed some CDI beans to requestscoped to keep them in order

rest/src/main/java/fi/otavanopisto/pyramus/rest/StudentRESTService.java
=> Let students access their assessment requests across study programs

pyramus/src/main/webapp/templates/generic/ajax_support.jsp, pyramus/src/test/java/fi/otavanopisto/pyramus/rest/AbstractRESTPermissionsTest.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/filter/SecurityFilter.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/session/RestSessionControllerImpl.java
* Removed oauth restrictions from rest filter and relying on RestSessionController to return null if the logged user cannot be resolved.
* Added ajax_support which adds (at the moment) axios (https://github.com/axios/axios) for more convenient ajax calls independent of any other libraries.
=> Rest session auth

persistence/src/main/java/fi/otavanopisto/pyramus/dao/DAOFactory.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/base/OrganizationDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/base/Organization.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/settings/CreateOrganizationViewController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/settings/EditOrganizationViewController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/settings/ManageOrganizationsViewController.java, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/javascriptlocale.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/javascriptlocale_fi_FI.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale_fi_FI.properties, pyramus/src/main/resources/pagemapping.properties, pyramus/src/main/webapp/scripts/gui/settings/manageorganizations.js, pyramus/src/main/webapp/templates/generic/ajax_support.jsp, pyramus/src/main/webapp/templates/generic/head_generic.jsp, pyramus/src/main/webapp/templates/settings/createorganization.jsp, pyramus/src/main/webapp/templates/settings/editorganization.jsp, pyramus/src/main/webapp/templates/settings/manageorganizations.jsp, pyramus/src/test/java/fi/otavanopisto/pyramus/rest/AbstractRESTPermissionsTest.java, pyramus/updates/in_devel/ftr-organization.sql, rest-model/src/main/java/fi/otavanopisto/pyramus/rest/model/Organization.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/ObjectFactory.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/OrganizationRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/permissions/OrganizationPermissions.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/filter/SecurityFilter.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/session/RestSessionControllerImpl.java
=> Organization base entity

framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiAikuistenPerusopetuksenStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiLukioStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/koodisto/ArviointiasteikkoYleissivistava.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/apa/KoskiAPAStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/internetix/KoskiInternetixLukioStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/internetix/KoskiInternetixPkStudentHandler.java, pyramus/src/test/java/fi/otavanopisto/pyramus/koski/KoskiCommonTests.java
Calculating averages from Set is not a good idea mmkay?
Closes #801
=> Fixed bug with mean grade calculation

framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiAikuistenPerusopetuksenStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiLukioStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/StudentSubjectSelections.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/apa/KoskiAPAStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/internetix/KoskiInternetixLukioStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/internetix/KoskiInternetixPkStudentHandler.java
=> 805 subject s credits

framework/src/main/java/fi/otavanopisto/pyramus/koski/model/apa/APAKurssinSuoritus.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/apa/KoskiAPAStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/internetix/KoskiInternetixPkStudentHandler.java
Repeat is the mother of learning.
Closes #811
=> Added transfercredit support to APA and Internetix/pk

pyramus/src/main/webapp/css/layout.css
=> * Added padding to container so privacy policy wont cover submit

framework/src/main/java/fi/otavanopisto/pyramus/koski/model/apa/KoskiAPAStudentHandler.java
=> Fixed silly bug

framework/src/main/java/fi/otavanopisto/pyramus/applications/ApplicationUtils.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/applications/ViewApplicationViewController.java, pyramus/src/main/webapp/templates/applications/form-sections/application-form-section-additional.jsp
=> Aikuisten perusopetuksen lukutaitovaihe

pyramus/src/main/webapp/templates/applications/management-fragment-actions.jsp
=> Allow transferring as student after school approval

framework/src/main/java/fi/otavanopisto/pyramus/applications/ApplicationUtils.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/applications/ViewApplicationViewController.java, pyramus/src/main/webapp/templates/applications/form-sections/application-form-section-additional.jsp
=> Applications: More detailed previous studies for nettilukio

framework/src/main/java/fi/otavanopisto/pyramus/applications/ApplicationUtils.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/application/ApplicationAttachmentDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/application/ApplicationAttachment.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/SaveApplicationJSONRequestController.java, pyramus/src/main/webapp/scripts/gui/applications/application-management.js, pyramus/src/main/webapp/scripts/gui/applications/application.js, pyramus/src/main/webapp/templates/applications/form-sections/application-form-section-attachments.jsp, pyramus/src/main/webapp/templates/applications/form-templates/application-form-template-file.jsp, pyramus/updates/66.001/180824_application_attachments.xml, rest/src/main/java/fi/otavanopisto/pyramus/rest/ApplicationRESTService.java
- resolves #836
- attachment description support
=> Applications: Attachments element reordering and description support

pyramus/src/main/webapp/templates/applications/management-fragment-actions.jsp
=> Allow rejecting an application after school approval (should applicant choose to decline)

framework/src/main/java/fi/otavanopisto/pyramus/applications/ApplicationUtils.java, framework/src/main/java/fi/otavanopisto/pyramus/applications/DuplicatePersonException.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/SaveApplicationJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/UpdateApplicationStateJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/applications/ViewApplicationViewController.java, pyramus/src/main/webapp/css/application-attachment.css, pyramus/src/main/webapp/css/application-desktop-xl.css, pyramus/src/main/webapp/css/application-desktop.css, pyramus/src/main/webapp/css/application-tablet.css, pyramus/src/main/webapp/scripts/gui/applications/application.js, pyramus/src/main/webapp/templates/applications/application-edit-gateway.jsp, pyramus/src/main/webapp/templates/applications/createcredentials.jsp, pyramus/src/main/webapp/templates/applications/form-sections/application-form-section-additional.jsp, pyramus/src/main/webapp/templates/applications/form-templates/application-form-template-file.jsp, rest/src/main/java/fi/otavanopisto/pyramus/rest/ApplicationRESTService.java
- user interface fine-tuning
- changed lodging checkboxes to mandatory dropdown fields
- fixed a bug when application contains just one attachment
- added notifications for when an application line is changed (by applicant or handler)
- prevent student creation for staff member accounts
=> Applications review changes

pyramus/src/main/webapp/templates/applications/index.jsp
=> Applications: Aikuislukio intro

pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/SearchStudentsJSONRequestContoller.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/SearchStudentsDialogViewController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/SearchStudentsViewController.java
* Show only study programmes in the student search fields the user has access to
* Show only study programmes in the student search results the user has access to
Closes #827
=> 827 searchstudents organization

bom/pom.xml, persistence/src/main/java/fi/otavanopisto/pyramus/dao/students/StudentGroupDAO.java, pom.xml, pyramus/src/test/java/fi/otavanopisto/pyramus/rest/StudentGroupPermissionTestsIT.java, pyramus/src/test/java/fi/otavanopisto/pyramus/rest/StudentGroupTestsIT.java, pyramus/src/test/resources/rest-data.sql, rest/src/main/java/fi/otavanopisto/pyramus/rest/StudentRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/StudentGroupController.java
=> 850 fix tests

pyramus/src/main/java/fi/otavanopisto/pyramus/views/applications/ViewApplicationViewController.java, pyramus/src/main/webapp/templates/applications/management-fragment-actions.jsp
=> Re-added missing application actions for aineopiskelu

framework/src/main/java/fi/otavanopisto/pyramus/applications/ApplicationUtils.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/SaveApplicationJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/UpdateApplicationStateJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/applications/CompleteApplicationViewController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/applications/SignedAcceptanceDocumentViewController.java, pyramus/src/main/webapp/css/application-form.css, pyramus/src/main/webapp/css/application-mobile.css, pyramus/src/main/webapp/templates/applications/application-edit.jsp, pyramus/src/main/webapp/templates/applications/form-sections/application-form-section-additional.jsp, pyramus/src/main/webapp/templates/applications/form-sections/application-form-section-attachments.jsp, pyramus/src/main/webapp/templates/applications/form-sections/application-form-section-done.jsp, pyramus/src/main/webapp/templates/applications/form-sections/application-form-section-internetix-school.jsp, pyramus/src/main/webapp/templates/applications/form-sections/application-form-section-personal-info.jsp, pyramus/src/main/webapp/templates/applications/form-sections/application-form-section-selection.jsp, pyramus/src/main/webapp/templates/applications/form-sections/application-form-section-source.jsp, pyramus/src/main/webapp/templates/applications/form-sections/application-form-section-summary.jsp, pyramus/src/main/webapp/templates/applications/form-sections/application-form-section-underage.jsp, pyramus/src/main/webapp/templates/applications/index.jsp, rest/src/main/java/fi/otavanopisto/pyramus/rest/ApplicationRESTService.java
- fixes #871
- added a clearer log entry when either applicant or handler changes application line
=> Element visibility fixes and better history for line changes

pyramus/src/main/webapp/templates/applications/management-fragment-header.jsp
=> Disable application edit/lock/unlock once student has been created

framework/src/main/java/fi/otavanopisto/pyramus/applications/ApplicationUtils.java
=> Log entry if Internetix applicant's school is not yet in Pyramus

persistence/src/main/java/fi/otavanopisto/pyramus/dao/DAOFactory.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/users/EmailSignatureDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/users/EmailSignature.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/SendMailJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/users/CreateEmailSignatureViewController.java, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale_fi_FI.properties, pyramus/src/main/resources/pagemapping.properties, pyramus/src/main/webapp/css/application-management-mobile.css, pyramus/src/main/webapp/templates/generic/header.jsp, pyramus/src/main/webapp/templates/users/createemailsignature.jsp, pyramus/updates/67.001/181008_email_signatures.xml
=> Email signatures

pyramus/src/main/webapp/templates/applications/mails/mail-confirmation-nettilukio-content.html, pyramus/src/main/webapp/templates/applications/mails/mail-confirmation-nettipk-content.html
=> Added two week handling period notice for nettilukio and nettiperuskoulu

pyramus/src/main/webapp/scripts/gui/applications/application.js, pyramus/src/main/webapp/templates/applications/form-sections/application-form-section-attachments.jsp, rest/src/main/java/fi/otavanopisto/pyramus/rest/ApplicationRESTService.java
=> Double the application attachment size limit

framework/src/main/java/fi/otavanopisto/pyramus/applications/ApplicationUtils.java
=> Non-contract school information to student's additional information

framework/src/main/java/fi/otavanopisto/pyramus/applications/ApplicationUtils.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/ApplicationRESTService.java
=> Include applicant name in notification email subjects

pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/ListLogEntriesJSONRequestController.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/ApplicationRESTService.java
- log confirmation mail; resolves #879
- sort log entries from newest to oldest
=> Add application received mail to application log

framework/src/main/java/fi/otavanopisto/pyramus/koski/model/apa/KoskiAPAStudentHandler.java
=> Added APA subjects starting with L to subjects list

pyramus/src/main/webapp/scripts/gui/applications/application.js, pyramus/src/main/webapp/templates/applications/form-sections/application-form-section-personal-info.jsp
=> Email verification field to applications

framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiSettings.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/internetix/KoskiInternetixLukioStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/internetix/KoskiInternetixPkStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/internetix/KoskiInternetixStudentHandler.java
=> Changes to Koski-integration

framework/src/main/java/fi/otavanopisto/pyramus/applications/ApplicationUtils.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/application/ApplicationDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/application/ApplicationSignaturesDAO.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/ArchiveApplicationJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/UpdateApplicationStateJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/ArchiveStudentJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/EditStudentJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/applications/MonthlySourceSummary.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/applications/RemoveOldApplicationsScheduler.java, pyramus/src/main/webapp/scripts/gui/applications/application-management.js
- resolves #4226 (https://github.com/otavanopisto/muikku/issues/4226)
=> Remove old applications

persistence/src/main/java/fi/otavanopisto/pyramus/dao/application/ApplicationLogDAO.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/ListLogEntriesJSONRequestController.java
=> Fix for application removal when studies end

persistence/src/main/java/fi/otavanopisto/pyramus/dao/base/EducationSubtypeDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/courses/CourseStudentDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/grading/TransferCreditDAO.java, rest-model/src/main/java/fi/otavanopisto/pyramus/rest/model/StudentMatriculationEligibility.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/StudentRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/AssessmentController.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/CommonController.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/CourseController.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/MatriculationEligibilityController.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/StudentMatriculationEligibilityResult.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/matriculation/MatriculationEligibilityCurriculumMapping.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/matriculation/MatriculationEligibilityMapping.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/matriculation/MatriculationEligibilitySubjectMapping.java, rest/src/main/resources/fi/otavanopisto/pyramus/rest/matriculation-eligibility-mapping.json
=> Ftr 911 matriculation eligibility endpoint

pyramus/src/main/webapp/scripts/gui/applications/application.js, pyramus/updates/70.001/181211_applications.xml, rest/src/main/java/fi/otavanopisto/pyramus/rest/ApplicationRESTService.java
=> Applications: Up attachment size limit and make it changeable from UI

framework/src/main/java/fi/otavanopisto/pyramus/applications/ApplicationUtils.java, framework/src/main/java/fi/otavanopisto/pyramus/framework/PyramusFileUtils.java, framework/src/main/java/fi/otavanopisto/pyramus/framework/SettingUtils.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/file/StudentFileDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/file/File.java, pyramus/src/main/java/fi/otavanopisto/pyramus/binary/studentfiles/DownloadStudentFile.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/studentfiles/EditStudentFileJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/studentfiles/UploadStudentFileJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/studentfiles/UploadStudentReportJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/studentfiles/MoveStudentFilesViewController.java, pyramus/src/main/resources/pagemapping.properties, pyramus/updates/71.001/181214_student-files.xml, webservices-plugin/src/main/java/fi/pyramus/services/FileService.java
=> Support and migration tool for file system student files

persistence/src/main/java/fi/otavanopisto/pyramus/dao/grading/CourseAssessmentDAO.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/courses/SaveCourseAssessmentsJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/grading/SaveCourseAssessmentJSONRequestController.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/AssessmentController.java
=> Fix archived course assessments causing database constraint violations

pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/EditStudentJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/users/CreateUserJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/users/EditUserJSONRequestController.java, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale_fi_FI.properties
=> Username availability check

framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/internetix/KoskiInternetixLukioStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/internetix/KoskiInternetixPkStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/settings/KoskiStudyProgrammeHandlerParams.java
=> 928 handler oids

rest/src/main/resources/fi/otavanopisto/pyramus/rest/matriculation-eligibility-mapping.json
=> Fixed AI subjectcode

pyramus/src/main/webapp/templates/applications/index.jsp
=> BUG-938 Privacy policy link

pyramus/src/main/java/fi/otavanopisto/pyramus/views/applications/MonthlySourceSummary.java
=> Applications: Monthly source summary per line

persistence/src/main/java/fi/otavanopisto/pyramus/dao/DAOFactory.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/students/StudentSubjectGradeDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/students/StudentSubjectGrade.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/ArchiveStudentJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/EditStudentSubjectGradeJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/EditStudentSubjectGradeDialogViewController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/ViewStudentViewController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/tor/StudentTOR.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/tor/TORCourse.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/tor/TORCredit.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/tor/TORCreditType.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/tor/TORSubject.java, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale_fi_FI.properties, pyramus/src/main/resources/jsonmapping.properties, pyramus/src/main/resources/pagemapping.properties, pyramus/src/main/webapp/css/viewstudent-subjectcredits.css, pyramus/src/main/webapp/templates/students/editstudent.jsp, pyramus/src/main/webapp/templates/students/editstudentsubjectgradedialog.jsp, pyramus/src/main/webapp/templates/students/viewstudent.jsp, pyramus/updates/72.001/190123_studentsubjectgrade.xml, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/UserController.java
=> 926 subject credits

pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/ViewStudentViewController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/tor/TORSubject.java, pyramus/src/main/webapp/templates/students/viewstudent.jsp
Fixes a NPE from viewstudent and cleans up some issues from viewing the data
=> Bug viewstudent subjectcredits

framework/src/main/java/fi/otavanopisto/pyramus/applications/ApplicationUtils.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/SaveApplicationJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/UpdateApplicationStateJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/applications/ViewApplicationViewController.java, pyramus/src/main/webapp/templates/applications/form-sections/application-form-section-underage.jsp, rest/src/main/java/fi/otavanopisto/pyramus/rest/ApplicationRESTService.java
=> Applications: Email validation changes

pyramus/src/main/webapp/scripts/gui/applications/application.js, pyramus/src/main/webapp/templates/applications/form-sections/application-form-section-underage.jsp
=> Applications: Email validation

pyramus/src/main/webapp/scripts/gui/applications/application.js
=> Applications: More accurate birthday validation

common/src/main/java/fi/otavanopisto/pyramus/events/StudentSubjectGradeEvent.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiEventListeners.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/OppiaineenSuoritusWithSubject.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/aikuistenperusopetus/KoskiAikuistenPerusopetuksenStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/apa/KoskiAPAStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/internetix/KoskiInternetixLukioStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/internetix/KoskiInternetixPkStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/lukio/KoskiLukioStudentHandler.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/students/StudentSubjectGradeDAO.java
=> Added Student update to Koski when subject grade changes

pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/ViewStudentViewController.java
=> Added curriculum filtering to subject credits tab

pyramus/updates/75.001/190307_matriculationExamEnrollmentDateVariable.xml
=> Added Matriculation Exam Enrollment Date Variable

persistence/src/main/java/fi/otavanopisto/pyramus/dao/DAOFactory.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/matriculation/MatriculationExamAttendanceDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/matriculation/MatriculationExamDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/matriculation/MatriculationExamSubjectSettingsDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/projects/StudentProjectDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/TSB.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/matriculation/MatriculationExam.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/matriculation/MatriculationExamAttendance.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/matriculation/MatriculationExamSubjectSettings.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/matriculation/ArchiveMatriculationAttendanceJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/matriculation/EditEnrollmentViewController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/matriculation/MatriculationExamSettingsViewController.java, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale_fi_FI.properties, pyramus/src/main/resources/jsonmapping.properties, pyramus/src/main/webapp/templates/matriculation/management-edit-enrollment.jsp, pyramus/src/main/webapp/templates/matriculation/management-enrollment-settings.jsp, pyramus/updates/76.001/190311_matriculationexamsubjectsettings.xml
=> 964 matriculation projects

persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/matriculation/MatriculationExamEnrollment.java, pyramus/updates/77.001/190314-enrollment-table.xml, rest/src/main/java/fi/otavanopisto/pyramus/rest/MatriculationRESTService.java
=> Fixed MatriculationExamEnrollment entity/DB discrepancy

persistence/src/main/java/fi/otavanopisto/pyramus/dao/matriculation/MatriculationExamEnrollmentDAO.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/matriculation/SearchEnrollmentsJSONRequestController.java, pyramus/src/main/webapp/templates/matriculation/management-browse-enrollments.jsp
=> Filter to find students with less than 20 mandatory courses done

pyramus/src/main/webapp/templates/matriculation/management-edit-enrollment.jsp
=> Fixed bug with checkbox values not saving

pyramus/src/main/java/fi/otavanopisto/pyramus/views/matriculation/EditEnrollmentViewController.java
=> Added check for undefined exam date

framework/src/main/java/fi/otavanopisto/pyramus/framework/DateUtils.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/matriculation/MatriculationExamDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/matriculation/MatriculationExam.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/matriculation/EditEnrollmentViewController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/matriculation/MatriculationExamSettingsViewController.java, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale_fi_FI.properties, pyramus/src/main/webapp/templates/matriculation/management-edit-enrollment.jsp, pyramus/src/main/webapp/templates/matriculation/management-enrollment-settings.jsp, pyramus/updates/78.001/190319-matriculationexamterm.xml, rest/src/main/java/fi/otavanopisto/pyramus/rest/MatriculationRESTService.java
=> Added term information for ENROLLED attendances

pyramus/src/main/webapp/templates/students/editstudent.jsp
Select field change was bound to click event which caused all sorts of problems.
=> Changed to proper event type observation

pyramus/src/main/webapp/templates/matriculation/management-edit-enrollment.jsp
=> Unified canPublishName selection with Muikku enrollment form

framework/src/main/resources/fi/otavanopisto/pyramus/ytl/ytl_ainekoodit.json, persistence/src/main/java/fi/otavanopisto/pyramus/dao/base/SubjectDAO.java
* Added RUB1 and RUB3 to RUx subjects
* Added code to subject search fields
=> YTL RUB1/RUB3 subjects

framework/src/main/java/fi/otavanopisto/pyramus/koski/model/internetix/KoskiInternetixLukioStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/internetix/KoskiInternetixPkStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/settings/KoskiStudyProgrammeHandlerParams.java
=> Added support for handler-specific mandatory subjects

framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiSettings.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/aikuistenperusopetus/KoskiAikuistenPerusopetuksenStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/apa/KoskiAPAStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/internetix/KoskiInternetixLukioStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/internetix/KoskiInternetixPkStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/lukio/KoskiLukioStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/settings/KoskiIntegrationSettings.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/settings/StudyEndReasonMapping.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/koski/KoskiPersonState.java, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale_fi_FI.properties
=> 999 koski apa valmistuminen

pyramus/updates/81.001/190610-application-emoji.xml
=> Emoji support for applications

framework/src/main/java/fi/otavanopisto/pyramus/applications/ApplicationUtils.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/DAOFactory.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/base/SchoolDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/students/StudentGroupDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/system/ConfigurationDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/system/Configuration.java, pyramus/pom.xml, pyramus/src/main/java/fi/otavanopisto/pyramus/views/applications/ConfigurationViewController.java, pyramus/src/main/resources/pagemapping.properties, pyramus/src/main/webapp/templates/applications/configuration.jsp, pyramus/updates/82.001/190618-configuration.xml
=> Framework for adding students to student groups based on school

pyramus/src/main/webapp/templates/students/editstudent.jsp, pyramus/src/main/webapp/templates/users/createuser.jsp, pyramus/src/main/webapp/templates/users/edituser.jsp
- resolves #1010 (as odd as it seems)
=> Browser autocomplete fix for credential fields

persistence/src/main/java/fi/otavanopisto/pyramus/dao/matriculation/MatriculationExamAttendanceDAO.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/matriculation/SearchEnrollmentsJSONRequestController.java, pyramus/src/main/webapp/templates/matriculation/management-browse-enrollments.jsp, pyramus/src/main/webapp/templates/matriculation/management-edit-enrollment.jsp
=> 1013 matriculation guider

persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/students/Sex.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/CreateStudentJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/EditStudentJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/util/dataimport/DataImportUtils.java, pyramus/src/main/java/fi/otavanopisto/pyramus/util/dataimport/scripting/api/PersonAPI.java, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale_fi_FI.properties, pyramus/src/main/webapp/templates/students/createstudent.jsp, pyramus/src/main/webapp/templates/students/editstudent.jsp, pyramus/src/main/webapp/templates/students/viewstudent.jsp, rest-model/src/main/java/fi/otavanopisto/pyramus/rest/model/Sex.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/ObjectFactory.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/PersonRESTService.java
=> Added OTHER to Sex

framework/src/main/java/fi/otavanopisto/pyramus/applications/ApplicationUtils.java, pyramus/src/main/webapp/scripts/gui/applications/application.js, pyramus/src/main/webapp/templates/applications/form-sections/application-form-section-personal-info.jsp
=> Always allow other gender in applications

pyramus/src/main/java/fi/otavanopisto/pyramus/json/matriculation/SearchEnrollmentsJSONRequestController.java, pyramus/src/main/webapp/templates/matriculation/management-browse-enrollments.jsp
=> Added approvedByGuider to searchresults

rest/src/main/java/fi/otavanopisto/pyramus/rest/ApplicationRESTService.java
=> Only log erroneous application form data

framework/src/main/java/fi/otavanopisto/pyramus/koski/model/internetix/KoskiInternetixLukioStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/lukio/KoskiLukioStudentHandler.java
=> MAY as part of MAA/MAB

framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiStudentHandler.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/ListKoskiPersonStudiesJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/ListKoskiPersonVariablesJSONRequestController.java
* Fixes Koski invalidation issue when studyprogramme has been removed
* Fixes NPE with Koski dialog when student has unconfigured studyprogrammes
Closes #1033
=> 1033 invalidation bug

framework/src/main/java/fi/otavanopisto/pyramus/framework/BinaryRequestController.java, framework/src/main/java/fi/otavanopisto/pyramus/framework/JSONRequestController.java, framework/src/main/java/fi/otavanopisto/pyramus/framework/JSONRequestController2.java, framework/src/main/java/fi/otavanopisto/pyramus/framework/PyramusRequestControllerAccess.java, framework/src/main/java/fi/otavanopisto/pyramus/framework/PyramusViewController.java, framework/src/main/java/fi/otavanopisto/pyramus/framework/PyramusViewController2.java, framework/src/main/java/fi/otavanopisto/pyramus/framework/UserUtils.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/base/Defaults.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/EditStudentGroupJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/EditStudentJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/EditStudentGroupViewController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/EditStudentViewController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/ViewStudentGroupViewController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/ViewStudentViewController.java, pyramus/updates/in_devel/ftr-organization.sql
=> 1035 organization restriction

pyramus/updates/85.001/281019-dang-emojis.xml
=> Assessment request emoji support

pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale.properties
=> Fixed Create Student Group locale

pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/OnnistuuClient.java, pyramus/src/main/webapp/templates/applications/application-accept.jsp, pyramus/src/main/webapp/templates/applications/application-done.jsp, pyramus/src/main/webapp/templates/applications/application-edit-gateway.jsp, pyramus/src/main/webapp/templates/applications/createcredentials.jsp, pyramus/src/main/webapp/templates/applications/document-acceptance-nettilukio.html, pyramus/src/main/webapp/templates/applications/document-acceptance-nettipk.html
=> Application Brand changes

framework/src/main/java/fi/otavanopisto/pyramus/security/impl/AbstractPermissionResolver.java
=> Removed Stateless from AbstractPermissionResolver

pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/CopyStudentStudyProgrammeJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/StudyProgrammeCopyPopupViewController.java, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale_fi_FI.properties, pyramus/src/main/webapp/templates/students/editstudent.jsp, pyramus/src/main/webapp/templates/students/studyprogrammecopypopup.jsp
Seems like browser autocompletion was the issue where the fields of a new (copied) study programme looked like filled when in database they never were. For some reason the fields are autofilled even when the field names are different for the new study programme......
Also added study programme selection to the copy dialog as the study programme is often the one changing in the copy. (Also has potential issues with Koski-integration.)
Closes #1060
=> 1060 copystudyprogramme issues

pyramus/src/main/webapp/templates/applications/management-fragment-actions.jsp
=> Allow rejecting applications even after the applicant has accepted

rest-model/src/main/java/fi/otavanopisto/pyramus/rest/model/muikku/StudentPayload.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/MuikkuRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/PersonController.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/permissions/MuikkuPermissions.java, rest/src/main/resources/messages_en.properties, rest/src/main/resources/messages_fi.properties
=> Rudimentary student creation support

pyramus/src/main/webapp/templates/students/viewstudent.jsp
The table caption was always present for all tabs but the table was only populated with values to the first tab.
=> Fixed personvariables table showing values on all tabs

framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiClient.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/aikuistenperusopetus/KoskiAikuistenPerusopetuksenStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/apa/KoskiAPAStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/internetix/KoskiInternetixLukioStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/internetix/KoskiInternetixPkStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/internetix/KoskiInternetixStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/lukio/KoskiLukioStudentHandler.java
=> Fixed removal of invalidated oid for internetix students

framework/src/main/java/fi/otavanopisto/pyramus/applications/ApplicationUtils.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/OnnistuuClient.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/UpdateApplicationStateJSONRequestController.java, pyramus/src/main/webapp/templates/applications/application-edit-gateway.jsp, pyramus/src/main/webapp/templates/applications/form-sections/application-form-section-done.jsp, pyramus/src/main/webapp/templates/applications/mails/mail-accept-study-place.html, pyramus/src/main/webapp/templates/applications/mails/mail-confirmation-nettilukio-content.html, pyramus/src/main/webapp/templates/applications/mails/mail-confirmation-nettipk-content.html, pyramus/src/main/webapp/templates/applications/mails/mail-credentials-create.html, pyramus/src/main/webapp/templates/applications/mails/mail-credentials-exist.html
=> Applications Otavia changes

framework/src/main/java/fi/otavanopisto/pyramus/applications/ApplicationUtils.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/students/StudentDAO.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/applications/ViewApplicationViewController.java, pyramus/src/main/webapp/templates/applications/form-sections/application-form-section-additional.jsp
=> New field for aineopiskelu applicants

persistence/src/main/java/fi/otavanopisto/pyramus/dao/base/StudyProgrammeDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/base/StudyProgramme.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/settings/SaveStudyProgrammesJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/util/dataimport/scripting/api/StudyProgrammeAPI.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/settings/StudyProgrammesViewController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/system/setupwizard/StudyProgrammesSetupWizardViewController.java, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/javascriptlocale.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/javascriptlocale_fi_FI.properties, pyramus/src/main/webapp/scripts/gui/settings/studyprogrammes.js, pyramus/src/test/java/fi/otavanopisto/pyramus/rest/AbstractRESTServiceTestTools.java, pyramus/src/test/java/fi/otavanopisto/pyramus/rest/StudyProgrammePermissionTestsIT.java, pyramus/src/test/java/fi/otavanopisto/pyramus/rest/StudyProgrammeTestsIT.java, pyramus/src/test/resources/rest-data.sql, pyramus/updates/88.001/200116_studyprogamme_hasevaluationfees.xml, rest-model/src/main/java/fi/otavanopisto/pyramus/rest/model/StudyProgramme.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/ObjectFactory.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/StudentRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/StudyProgrammeController.java
Muikku requires https://github.com/otavanopisto/muikku/pull/4866 to be merged at the same time
=> Added hasEvaluationFees to StudyProgramme

framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiSettings.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/aikuistenperusopetus/KoskiAikuistenPerusopetuksenStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/apa/KoskiAPAStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/internetix/KoskiInternetixLukioStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/lukio/KoskiLukioStudentHandler.java
* Unified rahoitus handling
* Added yksityisopiskelija boolean to mark students of a study programme with this tag
=> Added yksityisopiskelija boolean for studyprogrammes

rest/src/main/java/fi/otavanopisto/pyramus/rest/MuikkuRESTService.java
=> Duplicate credential fix

framework/src/main/java/fi/otavanopisto/pyramus/applications/ApplicationUtils.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/applications/ViewApplicationViewController.java, pyramus/src/main/webapp/templates/applications/application-form.jsp, pyramus/src/main/webapp/templates/applications/form-sections/application-form-section-selection.jsp, pyramus/src/main/webapp/templates/applications/management-edit-application.jsp
=> Private student selection to application approval

pyramus/src/main/webapp/templates/applications/form-sections/application-form-section-summary.jsp, pyramus/src/main/webapp/templates/applications/index.jsp, pyramus/src/main/webapp/templates/generic/footer.jsp
=> Privacy urls

persistence/src/main/java/fi/otavanopisto/pyramus/dao/students/StudentGroupDAO.java
=> Give out a holler when a user group gets archived

pyramus/src/main/java/fi/otavanopisto/pyramus/binary/ytl/YTLReportBinaryRequestController.java
=> Added MAY to YTL json under selected math subject

pyramus/src/test/java/fi/otavanopisto/pyramus/rest/StudentStudyPeriodPermissionsTestsIT.java, pyramus/src/test/java/fi/otavanopisto/pyramus/rest/StudentStudyPeriodTestsIT.java, rest-model/src/main/java/fi/otavanopisto/pyramus/rest/model/students/StudentStudyPeriod.java, rest-model/src/main/java/fi/otavanopisto/pyramus/rest/model/students/StudentStudyPeriodType.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/ObjectFactory.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/permissions/StudentPermissions.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/student/StudentStudyPeriodRESTService.java
Closes issue 985 although that implementation will be in Muikku.
Closes #985
=> Added rest endpoints for student study periods

pyramus/src/main/webapp/templates/students/viewstudent.jsp
=> Fixed issue with non-passing grade in subject credits

pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/EditStudentJSONRequestController.java
=> Credential deletion

pyramus/src/main/java/fi/otavanopisto/pyramus/views/applications/ViewApplicationViewController.java, pyramus/src/main/webapp/templates/applications/form-sections/application-form-section-underage.jsp
=> Application changes

pyramus/src/main/webapp/templates/applications/management-edit-application.jsp
=> Remove management actions during application edit

pyramus/src/test/java/fi/otavanopisto/pyramus/rest/MuikkuRestServicePermissionsTestsIT.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/MuikkuRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/permissions/MuikkuPermissions.java
=> Organization management study guider and study programme leader support

rest/src/main/java/fi/otavanopisto/pyramus/rest/MuikkuRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/StaffRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/permissions/MuikkuPermissions.java
=> Organization management edit student support + bug fixes

rest/src/main/java/fi/otavanopisto/pyramus/rest/ApplicationRESTService.java
=> Application referer NPE fix

pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/EditStudentJSONRequestController.java, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale_fi_FI.properties
=> Don't attempt to create credentials without password

framework/src/main/java/fi/otavanopisto/pyramus/koski/koodisto/Kielivalikoima.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/koodisto/KoskiOppiaineetYleissivistava.java
=> Updated Koski enums

pyramus/src/main/webapp/templates/applications/index.jsp
=> 1147 - Paikka ja toteutusmuoto saavutettavuusselosteelle

framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiClient.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiController.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/base/Person.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/base/PersonStudentComparator.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/ListKoskiPersonStudiesJSONRequestController.java
=> Fixes for few issues handling Koski-integration

pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/tor/TORCourse.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/tor/TORCredit.java, pyramus/src/main/webapp/templates/courses/editcourse.jsp, pyramus/src/test/java/fi/otavanopisto/pyramus/students/tor/TORCreditTests.java
=> 1134 subjectview credit

framework/src/main/java/fi/otavanopisto/pyramus/applications/ApplicationUtils.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/internetix/KoskiInternetixLukioStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/lukio/KoskiLukioStudentHandler.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/users/UserVariableDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/users/UserVariableKeyDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/users/UserVariable.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/users/UserVariableKey.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/CopyStudentStudyProgrammeJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/CreateStudentJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/util/dataimport/scripting/api/StudentAPI.java, pyramus/src/main/webapp/scripts/gui/students/createstudent.js, pyramus/updates/91.001/201009_uservariable_defaultvalue.xml, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/StudentController.java
=> Uservariable default values

framework/src/main/java/fi/otavanopisto/pyramus/applications/ApplicationUtils.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/SaveApplicationJSONRequestController.java, pyramus/src/main/webapp/templates/applications/mails/mail-modified-aikuislukio-content.html, pyramus/src/main/webapp/templates/applications/mails/mail-modified-aikuislukio-subject.txt, pyramus/src/main/webapp/templates/applications/mails/mail-modified-mk-content.html, pyramus/src/main/webapp/templates/applications/mails/mail-modified-mk-subject.txt, pyramus/src/main/webapp/templates/applications/mails/mail-modified-nettilukio-content.html, pyramus/src/main/webapp/templates/applications/mails/mail-modified-nettilukio-subject.txt, pyramus/src/main/webapp/templates/applications/mails/mail-modified-nettipk-content.html, pyramus/src/main/webapp/templates/applications/mails/mail-modified-nettipk-subject.txt, rest/src/main/java/fi/otavanopisto/pyramus/rest/ApplicationRESTService.java
=> Send mail to applicant if application edit credentials have changed

framework/src/main/java/fi/otavanopisto/pyramus/applications/AlternativeLine.java, framework/src/main/java/fi/otavanopisto/pyramus/applications/ApplicationUtils.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/applications/ViewApplicationViewController.java, pyramus/src/main/webapp/scripts/gui/applications/application-management.js, pyramus/src/main/webapp/templates/applications/form-sections/application-form-section-additional.jsp, pyramus/src/main/webapp/templates/applications/form-sections/application-form-section-selection.jsp
=> 1166 applications new features

bom/pom.xml
Seems to fix the issue with vintage engine complaining about version parse issues.
=> Bump to junit 5.7.0

pyramus/src/main/webapp/css/application-desktop-xl.css, pyramus/src/main/webapp/css/application-desktop.css, pyramus/src/main/webapp/css/application-mobile.css, pyramus/src/main/webapp/css/application-tablet.css, pyramus/src/main/webapp/scripts/gui/applications/application.js, pyramus/src/main/webapp/templates/applications/form-sections/application-form-section-summary.jsp
=> Added contact promise to application

pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/OnnistuuClient.java
=> Check application document signature status before signing

persistence/src/main/java/fi/otavanopisto/pyramus/dao/application/ApplicationDAO.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/SearchApplicationsJSONRequestController.java, pyramus/src/main/webapp/templates/applications/management-browse-applications.jsp
=> Added name field to application search

pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/EditStudentViewController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/ViewStudentViewController.java
=> Added sorting for periods

rest/src/main/java/fi/otavanopisto/pyramus/rest/MuikkuRESTService.java
=> Refactored student group member management endpoints

persistence/src/main/java/fi/otavanopisto/pyramus/dao/students/StudentGroupStudentDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/students/StudentGroupUserDAO.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/MuikkuRESTService.java
=> Various bug fixes for removing user group users

pyramus/src/main/webapp/css/application.css, pyramus/src/main/webapp/templates/applications/application-edit.jsp, pyramus/src/main/webapp/templates/applications/form-sections/application-form-section-additional.jsp, pyramus/src/main/webapp/templates/applications/form-sections/application-form-section-attachments.jsp, pyramus/src/main/webapp/templates/applications/form-sections/application-form-section-done.jsp, pyramus/src/main/webapp/templates/applications/form-sections/application-form-section-internetix-school.jsp, pyramus/src/main/webapp/templates/applications/form-sections/application-form-section-personal-info.jsp, pyramus/src/main/webapp/templates/applications/form-sections/application-form-section-selection.jsp, pyramus/src/main/webapp/templates/applications/form-sections/application-form-section-source.jsp, pyramus/src/main/webapp/templates/applications/form-sections/application-form-section-summary.jsp, pyramus/src/main/webapp/templates/applications/form-sections/application-form-section-underage.jsp, pyramus/src/main/webapp/templates/applications/index.jsp
=> 1151 application form labels

persistence/src/main/java/fi/otavanopisto/pyramus/dao/PyramusEntityDAO.java
=> Fix for special characters in Lucene queries

.github/workflows/deploy.yml
=> Shoots a webhook to staging after deployment is done

persistence/src/main/java/fi/otavanopisto/pyramus/dao/DAOFactory.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/users/StaffMemberDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/worklist/WorklistItemDAO.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/SearchStudentsJSONRequestContoller.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/worklist/ArchiveWorklistItemJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/worklist/ArchiveWorklistTemplateJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/worklist/EditWorklistItemJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/worklist/EditWorklistTemplateJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/worklist/ListWorklistItemsJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/worklist/AssessmentInfoViewController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/worklist/EditWorklistTemplateViewController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/worklist/ListWorklistItemsViewController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/worklist/ManageWorklistTemplatesViewController.java, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/javascriptlocale.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/javascriptlocale_fi_FI.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale_fi_FI.properties, pyramus/src/main/resources/jsonmapping.properties, pyramus/src/main/resources/pagemapping.properties, pyramus/src/main/webapp/css/layout.css, pyramus/src/main/webapp/scripts/gui/worklist/listworklistitems.js, pyramus/src/main/webapp/scripts/gui/worklist/manageworklisttemplates.js, pyramus/src/main/webapp/scripts/ixtable/ixtable.js, pyramus/src/main/webapp/templates/generic/header.jsp, pyramus/src/main/webapp/templates/worklist/assessmentinfo.jsp, pyramus/src/main/webapp/templates/worklist/editworklisttemplate.jsp, pyramus/src/main/webapp/templates/worklist/listworklistitems.jsp, pyramus/src/main/webapp/templates/worklist/manageworklisttemplates.jsp, rest/src/main/java/fi/otavanopisto/pyramus/rest/WorklistRESTService.java
- resolves #1200
- refactored templates from settings to worklist
=> Manage worklist items

pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/UpdateApplicationStateJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/applications/ViewApplicationViewController.java, pyramus/src/main/webapp/templates/applications/form-sections/application-form-section-additional.jsp
- resolves #1216 (remove signatures if application returned to processing)
- resolves #1222 (remove YO-tutkinto from application form)
=> Application customer requested changes and processing bug fix

framework/src/main/java/fi/otavanopisto/pyramus/framework/StaffMemberProperties.java, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale_fi_FI.properties, pyramus/src/main/webapp/scripts/gui/worklist/listworklistitems.js, pyramus/src/main/webapp/templates/worklist/listworklistitems.jsp, rest-model/src/main/java/fi/otavanopisto/pyramus/rest/model/worklist/WorklistApproverRestModel.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/WorklistRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/permissions/WorklistPermissions.java
- resolves #1230
- added query param based initial search for worklist management
=> Support for defining and returning worklist approvers

persistence/src/main/java/fi/otavanopisto/pyramus/dao/worklist/WorklistItemDAO.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/worklist/EditWorklistItemJSONRequestController.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/WorklistRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/WorklistController.java
- fixed wrong endpoint method
- reset state of edited items back to ENTERED
- resolves #1233
=> Worklist bug fixes

pyramus/src/main/webapp/scripts/gui/worklist/listworklistitems.js, pyramus/src/main/webapp/scripts/ixtable/ixtable.js
=> Fix for incorrect row removed when deleting a worklist item

pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/tor/StudentTOR.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/tor/StudentTORController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/tor/TORCourse.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/tor/TORCourseLengthUnit.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/tor/TORProblem.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/tor/TORProblemType.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/tor/TORProblems.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/tor/TORSubject.java, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/javascriptlocale.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/javascriptlocale_fi_FI.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale_fi_FI.properties, pyramus/src/main/webapp/css/viewstudent-subjectcredits.css, pyramus/src/main/webapp/templates/students/viewstudent.jsp
=> Preliminary support for weighted mean grade calculation

framework/src/main/java/fi/otavanopisto/pyramus/applications/ApplicationUtils.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/base/EmailDAO.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/ListExistingPersonsJSONRequestController.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/MuikkuRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/CommonController.java
=> Refactored email method that assumed addresses are unique

framework/src/main/java/fi/otavanopisto/pyramus/schedulers/ClientApplicationTokenCleaner.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/clientapplications/ClientApplicationAccessTokenDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/clientapplications/ClientApplicationAccessToken.java, pyramus/updates/102.001/210528_clientapplication_cleanup.xml
=> Clean up expired client application access tokens

pyramus/src/test/java/fi/otavanopisto/pyramus/rest/CoursePermissionsTestsIT.java, pyramus/src/test/java/fi/otavanopisto/pyramus/rest/CourseTestsIT.java, rest-model/src/main/java/fi/otavanopisto/pyramus/rest/model/Course.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/ObjectFactory.java
- resolves #1257
- needed by Muikku issue 5540
=> Added course's primary education type and subtype to REST model

rest/src/main/java/fi/otavanopisto/pyramus/rest/WorklistRESTService.java
=> Fix for a crash when asking course base price when they haven't been configured yet

pyramus/src/main/webapp/css/application-attachment.css, pyramus/src/main/webapp/css/application-management-mobile.css, pyramus/src/main/webapp/scripts/gui/applications/application-management.js
=> Allow removal of application attachments even after the applicant has been thrown in

persistence/src/main/java/fi/otavanopisto/pyramus/dao/application/ApplicationDAO.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/ChangeHandlerJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/applications/ChangeHandlerViewController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/applications/HandlerStatisticsViewController.java, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale_fi_FI.properties, pyramus/src/main/resources/jsonmapping.properties, pyramus/src/main/resources/pagemapping.properties, pyramus/src/main/webapp/scripts/gui/applications/changehandler.js, pyramus/src/main/webapp/templates/applications/changehandler.jsp, pyramus/src/main/webapp/templates/applications/handlerstatistics.jsp, pyramus/src/main/webapp/templates/generic/header.jsp, pyramus/updates/103.001/210603_application_handler_state.xml
=> Functionality to assign all in-progress applications from one handler to another

pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/EditStudentViewController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/SelectUserVariablePresetDialogViewController.java, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale_fi_FI.properties, pyramus/src/main/resources/pagemapping.properties, pyramus/src/main/webapp/css/theme.css, pyramus/src/main/webapp/templates/students/editstudent.jsp, pyramus/src/main/webapp/templates/students/selectuservariablepresetdialog.jsp
=> UserVariable Presets

pyramus/src/main/java/fi/otavanopisto/pyramus/views/reports/ViewReportParametersViewController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/reports/ViewReportViewController.java, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale_fi_FI.properties, pyramus/src/main/webapp/scripts/gui/worklist/listworklistitems.js, pyramus/src/main/webapp/templates/reports/viewreport.jsp, pyramus/src/main/webapp/templates/worklist/listworklistitems.jsp
=> Worklist report button

framework/src/main/java/fi/otavanopisto/pyramus/security/impl/permissions/OrganizationPermissions.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/OrganizationRESTService.java
https://github.com/otavanopisto/muikku/pull/5613
=> Organization overview - contact person

framework/src/main/java/fi/otavanopisto/pyramus/applications/ApplicationUtils.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/ApplicationRESTService.java
=> Better filename sanitation

persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/students/StudentStudyPeriodType.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/EditStudentJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/EditStudentViewController.java, pyramus/src/main/webapp/templates/students/editstudent.jsp
=> 1284 disable studyperiod enddates

framework/src/main/java/fi/otavanopisto/pyramus/applications/ApplicationUtils.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/applications/ViewApplicationViewController.java, pyramus/src/main/webapp/scripts/gui/applications/application.js, pyramus/src/main/webapp/templates/applications/form-sections/application-form-section-personal-info.jsp, pyramus/src/main/webapp/templates/applications/form-sections/application-form-section-selection.jsp
=> Prefill compulsory periods from application acceptance

pyramus/src/main/java/fi/otavanopisto/pyramus/binary/students/StudentGroupsAutoCompleteBinaryRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/binary/students/StudyProgrammesAutoCompleteBinaryRequestController.java, pyramus/src/main/webapp/scripts/gui/courses/editcourse.js, rest-model/src/main/java/fi/otavanopisto/pyramus/rest/model/OrganizationBasicInfo.java, rest-model/src/main/java/fi/otavanopisto/pyramus/rest/model/course/CourseSignupStudentGroup.java, rest-model/src/main/java/fi/otavanopisto/pyramus/rest/model/course/CourseSignupStudyProgramme.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/CourseSignupRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/ObjectFactory.java
Requires https://github.com/otavanopisto/muikku/pull/5733
Closes #1297
=> Fixes to signup group management

pyramus/src/main/webapp/templates/applications/application-edit.jsp, pyramus/src/main/webapp/templates/applications/form-sections/application-form-section-attachments.jsp, pyramus/src/main/webapp/templates/applications/mails/mail-confirmation-nettilukio-content.html
=> Requested application wording changes

pyramus/src/test/java/fi/otavanopisto/pyramus/rest/MuikkuRestServicePermissionsTestsIT.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/MuikkuRESTService.java
=> User creation and update to only support managers and teachers (for now)

pyramus/src/main/webapp/templates/generic/footer.jsp
=> * Privacy policy link update

persistence/src/main/java/fi/otavanopisto/pyramus/dao/matriculation/MatriculationExamEnrollmentDAO.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/ViewStudentViewController.java, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale_fi_FI.properties, pyramus/src/main/webapp/templates/students/viewstudent.jsp
=> Added link(s) to students' matriculation exam enrollments to viewstudent

muikku-plugin/src/main/resources/fi/otavanopisto/pyramus/plugin/muikku/muikkulogin.ftl, muikku-plugin/src/main/resources/fi/otavanopisto/pyramus/plugin/muikku/muikkulogin_fi.ftl, muikku-plugin/src/main/resources/fi/otavanopisto/pyramus/plugin/muikku/muikkuloginhead.ftl
=> * Restyling of Muikku login screen

muikku-plugin/src/main/resources/fi/otavanopisto/pyramus/plugin/muikku/muikkulogin.ftl, muikku-plugin/src/main/resources/fi/otavanopisto/pyramus/plugin/muikku/muikkulogin_fi.ftl
=> * Login view's header text change

pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/OnnistuuClient.java, pyramus/src/main/webapp/templates/applications/document-acceptance-nettilukio.html
=> Requested application document wording changes + line specific primary signer support

smvcj/src/main/java/fi/internetix/smvc/controllers/RequestContext.java
=> NPE fix when resolving request referer

framework/src/main/java/fi/otavanopisto/pyramus/applications/ApplicationUtils.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/UpdateApplicationStateJSONRequestController.java
- less personal info logging
- removed special handling for rejected Internetix applications
- resolves #1355
=> Removed special handling for rejected Internetix applications

pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/ListMailRecipientsJSONRequestController.java
=> Add application mail support for secondary guardians

framework/src/main/java/fi/otavanopisto/pyramus/applications/ApplicationUtils.java, pyramus/src/main/webapp/scripts/gui/applications/application.js
- more accurate field checks when handling Internetix applicants
- resolves #1359
=> Additional logic to ignore application form fields that aren't shown

pyramus/src/main/java/fi/otavanopisto/pyramus/binary/applications/GetDocumentBinaryRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/GetDocumentUrlsJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/ListMailRecipientsJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/OnnistuuClient.java, pyramus/src/main/resources/binarymapping.properties
=> Proxy links for fetching application documents in application management

framework/src/main/java/fi/otavanopisto/pyramus/applications/ApplicationUtils.java
=> Application NPE fixes

rest-model/src/main/java/fi/otavanopisto/pyramus/rest/model/StudentContactLogEntry.java, rest-model/src/main/java/fi/otavanopisto/pyramus/rest/model/StudentContactLogEntryCommentRestModel.java
https://github.com/otavanopisto/muikku/pull/6117
=> Added field hasImage to contactLogEntry rest models

framework/src/main/java/fi/otavanopisto/pyramus/tor/StudentTOR.java, framework/src/main/java/fi/otavanopisto/pyramus/tor/StudentTORController.java, framework/src/main/java/fi/otavanopisto/pyramus/tor/TORCourse.java, framework/src/main/java/fi/otavanopisto/pyramus/tor/TORProblemType.java, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/javascriptlocale.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/javascriptlocale_fi_FI.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale_fi_FI.properties, rest/src/main/java/fi/otavanopisto/pyramus/rest/StudentRESTService.java
Fixed credit point counting to return only mandatory course credit count as it was supposed to (instead of all credits).
=> Fixed counting of credit points

persistence/src/main/java/fi/otavanopisto/pyramus/dao/students/StudentContactLogEntryDAO.java, pyramus/src/test/java/fi/otavanopisto/pyramus/rest/StudentContactLogEntryTestsIT.java, rest-model/src/main/java/fi/otavanopisto/pyramus/rest/model/StudentContactLogEntryBatch.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/ObjectFactory.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/StudentRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/StudentContactLogEntryController.java
https://github.com/otavanopisto/muikku/pull/6137
=> Sivutus yhteydenottoihin & järjestys uusimmasta vanhimpaan

persistence/src/main/java/fi/otavanopisto/pyramus/dao/base/StudyProgrammeDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/base/StudyProgramme.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/settings/SaveStudyProgrammesJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/util/dataimport/scripting/api/StudyProgrammeAPI.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/settings/StudyProgrammesViewController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/system/setupwizard/StudyProgrammesSetupWizardViewController.java, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/javascriptlocale.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/javascriptlocale_fi_FI.properties, pyramus/src/main/webapp/scripts/gui/settings/studyprogrammes.js, pyramus/src/test/java/fi/otavanopisto/pyramus/rest/AbstractRESTServiceTestTools.java, pyramus/src/test/java/fi/otavanopisto/pyramus/rest/StudyProgrammePermissionTestsIT.java, pyramus/src/test/java/fi/otavanopisto/pyramus/rest/StudyProgrammeTestsIT.java, pyramus/updates/110.001/220602_officialedutype.xml, rest-model/src/main/java/fi/otavanopisto/pyramus/rest/model/StudyProgramme.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/ObjectFactory.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/StudentRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/StudyProgrammeController.java
=> Added officialEducationType to StudyProgramme

persistence/src/main/java/fi/otavanopisto/pyramus/dao/courses/CourseModuleDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/grading/CourseAssessmentDAO.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/StudentRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/WorklistRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/WorklistController.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/permissions/WorklistPermissions.java
=> Yhdistelmäopintojen moduulihinta samalle oppiaineelle

pyramus/src/main/webapp/templates/applications/mails/mail-accept-study-place.html
=> Hakemuspostien muotoilu

persistence/src/main/java/fi/otavanopisto/pyramus/dao/courses/CourseDAO.java
=> Do not return archived courses for staff members

framework/src/main/java/fi/otavanopisto/pyramus/applications/ApplicationUtils.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/applications/ViewApplicationViewController.java, pyramus/src/main/webapp/templates/applications/form-sections/application-form-section-additional.jsp
=> Remove LUVA from application options

persistence/src/main/java/fi/otavanopisto/pyramus/dao/base/SubjectDAO.java, pyramus/src/main/java/fi/otavanopisto/pyramus/binary/ytl/YTLReportBinaryRequestController.java
=> Archived checks for subject finder methods

persistence/src/main/java/fi/otavanopisto/pyramus/dao/courses/CourseDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/courses/Course.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/courses/CreateCourseJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/courses/EditCourseJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/courses/SearchCoursesJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/util/dataimport/scripting/api/CourseAPI.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/system/DebugDataViewController.java, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale_fi_FI.properties, pyramus/src/main/webapp/templates/courses/createcourse.jsp, pyramus/src/main/webapp/templates/courses/editcourse.jsp, pyramus/src/main/webapp/templates/courses/viewcourse.jsp, pyramus/updates/111.001/220902_Ilmoittautumisen_ajastaminen.xml, rest/src/main/java/fi/otavanopisto/pyramus/rest/CourseRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/CourseController.java
=> Ilmoittautumisen ajastaminen: Kentät ja tallennus Pyramukseen

pyramus/src/test/java/fi/otavanopisto/pyramus/rest/CoursePermissionsTestsIT.java, pyramus/src/test/java/fi/otavanopisto/pyramus/rest/CourseTestsIT.java, rest-model/src/main/java/fi/otavanopisto/pyramus/rest/model/Course.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/CourseRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/ObjectFactory.java
=> Ilmoittautumisen ajastaminen: Kentät Muikkuun

framework/src/main/java/fi/otavanopisto/pyramus/mailer/Mailer.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/OnnistuuClient.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/UpdateApplicationStateJSONRequestController.java, pyramus/src/main/webapp/templates/applications/document-student-signed-otava.html, pyramus/src/main/webapp/templates/applications/document-student-signed-otavia.html, pyramus/src/main/webapp/templates/applications/mails/mail-accept-study-place.html
=> Application document delivery changes

framework/src/main/java/fi/otavanopisto/pyramus/framework/UserUtils.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/base/PersonDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/users/StaffMemberDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/users/StaffMember.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/EditStudentJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/SearchStudentsDialogJSONRequestContoller.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/SearchStudentsJSONRequestContoller.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/users/CreateUserJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/users/EditUserJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/EditStudentViewController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/SearchStudentsViewController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/ViewStudentViewController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/users/CreateUserViewController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/users/EditUserViewController.java, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale_fi_FI.properties, pyramus/src/main/webapp/templates/generic/header.jsp, pyramus/src/main/webapp/templates/users/createuser.jsp, pyramus/src/main/webapp/templates/users/edituser.jsp, pyramus/updates/112.001/220926_staff-member-study-programme.xml, rest-model/src/main/java/fi/otavanopisto/pyramus/rest/model/StaffMember.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/ObjectFactory.java
- settings view for admins only
- student visibility based on staff study programme selection
- resolves #1416
=> Limit access to students via study programmes

pyramus/src/main/webapp/scripts/gui/applications/application.js, pyramus/src/main/webapp/templates/applications/form-sections/application-form-section-underage.jsp
=> Validation for non-mandatory email fields in applications

persistence/src/main/java/fi/otavanopisto/pyramus/dao/PyramusEntityDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/base/PersonDAO.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/SearchStudentsDialogJSONRequestContoller.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/SearchStudentsJSONRequestContoller.java
=> Fix for admins searching students

pyramus/src/main/webapp/scripts/gui/applications/application.js
=> Fix for application form dependent fields not showing even when they should

pyramus/src/main/java/fi/otavanopisto/pyramus/views/applications/ViewApplicationViewController.java, pyramus/src/main/webapp/templates/applications/form-sections/application-form-section-selection.jsp
=> Hakemukset: Käsittelijäkenttien arvot hakijan muokatessa hakemusta

rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/permissions/CoursePermissions.java
https://github.com/otavanopisto/muikku/issues/6410
=> Opettajille oikeudet muokata kurssin tietoja

framework/src/main/java/fi/otavanopisto/pyramus/applications/ApplicationUtils.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/GenerateAcceptanceDocumentJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/UpdateApplicationStateJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/applications/ViewApplicationViewController.java, pyramus/src/main/webapp/scripts/gui/applications/application.js
=> Hakemukset: Korjauksia kenttien näkyvyyteen ja käsittelyyn

pyramus/src/main/webapp/scripts/fnilocale/fnilocale-uncompressed.js, pyramus/src/main/webapp/templates/generic/locale_support.jsp
Fixes a problem where year was not rendered in places like
* Student contact log entries
* Improved grades popup
=> Fixes issue with date formats where year is designated with single y

framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiClient.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiConsts.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiStartupInitializer.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/apa/KoskiAPAStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/lukio/KoskiLukioStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/lukio/ops2019/AbstractKoskiLukioStudentHandler2019.java, pyramus/src/test/java/fi/otavanopisto/pyramus/rest/SchoolVariableTestsIT.java, pyramus/src/test/java/fi/otavanopisto/pyramus/rest/StudentVariableTestsIT.java
Closes #1442 
- Parannettu tukea aineoppimäärän suorituksille ja mahdollistettu, että näille voi merkitä päättymissyyksi myös "valmistunut".
- Lisätty yhteyksien sulkemistoiminnot ettei palvelin kitise
- Lisätty puuttuneita muuttujia käynnistyksessä tapahtuvaan alustukseen
=> Aineoppimäärään (Koski) liittyviä fiksejä

persistence/src/main/java/fi/otavanopisto/pyramus/dao/projects/StudentProjectDAO.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/ArchiveStudentJSONRequestController.java, pyramus/updates/117.001/230306_archive_studentprojects.xml
=> Student project search finds student projects even for archived students

persistence/src/main/java/fi/otavanopisto/pyramus/dao/base/PersonDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/base/Person.java
=> Student search query returns in wrong order

framework/src/main/java/fi/otavanopisto/pyramus/applications/ApplicationUtils.java, framework/src/main/java/fi/otavanopisto/pyramus/framework/StaffMemberProperties.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/application/ApplicationDAO.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/SaveApplicationJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/SearchApplicationsJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/SignAcceptanceDocumentJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/UpdateApplicationStateJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/taglib/ApplicationAccessTag.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/applications/ManageApplicationViewController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/applications/ViewApplicationViewController.java, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale_fi_FI.properties, pyramus/src/main/webapp/WEB-INF/ix.tld, pyramus/src/main/webapp/templates/applications/management-browse-applications.jsp, pyramus/src/main/webapp/templates/generic/header.jsp
=> Limit application menu, search, and access based on predefined user properties

pyramus/src/main/java/fi/otavanopisto/pyramus/binary/studentfiles/DownloadStudentFile.java, pyramus/src/main/webapp/templates/students/viewstudent.jsp
Aiemmin tiedostot on ladattu koneelle automaattisesti ja ilman tiedostopäätettä, nyt avataan suoraan uuteen välilehteen.
closes #1457
=> Opiskelijan tiedostot uuteen välilehteen lataamisen sijaan

pyramus/src/main/java/fi/otavanopisto/pyramus/json/users/CreateUserJSONRequestController.java
=> Staff member creation fails if only username is provided

framework/src/main/java/fi/otavanopisto/pyramus/framework/StaffMemberProperties.java, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale_fi_FI.properties, rest-model/src/main/java/fi/otavanopisto/pyramus/rest/model/StudentGuidanceRelation.java, rest-model/src/main/java/fi/otavanopisto/pyramus/rest/model/UserContactInfo.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/StudentRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/UserRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/permissions/StudentPermissions.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/permissions/UserPermissions.java
- resolves #1448
- required by Muikku issue 6501
=> Endpoints for student guidance relation and contact info

persistence/src/main/java/fi/otavanopisto/pyramus/dao/PyramusEntityDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/base/PersonDAO.java
=> Prevents email address splitting in search

framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiClient.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/model/deserializers/SuoritusDeserializer.java
=> Korjauksia mitätöintiin

rest/src/main/java/fi/otavanopisto/pyramus/rest/StudentRESTService.java
https://github.com/otavanopisto/muikku/pull/6563
Fixes problems with 403 when calling endpoint amICounselor
=> Contact info popover 

rest-model/src/main/java/fi/otavanopisto/pyramus/rest/model/SpecEdTeacher.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/StudentRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/permissions/StudentGroupPermissions.java
=> Endpoint to fetch special education teachers and optonally student's guidance councelors

pyramus/src/main/java/fi/otavanopisto/pyramus/json/settings/SaveStudyProgrammesJSONRequestController.java, pyramus/src/main/webapp/scripts/gui/settings/studyprogrammes.js, pyramus/src/main/webapp/templates/students/createstudent.jsp
=> Small UI fixes

pyramus/src/main/java/fi/otavanopisto/pyramus/json/courses/EditCourseJSONRequestController.java
=> Fixes course staff members being updated unnecessarily

.github/workflows/deploy.yml, .github/workflows/restTest.yml, .github/workflows/uiTests.yml
- don't set env variables and maven config when not needed
=> Update used actions version

pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/UpdateApplicationStateJSONRequestController.java, pyramus/updates/121.001/230905-assessment-price.xml, rest-model/src/main/java/fi/otavanopisto/pyramus/rest/model/course/CourseAssessmentPrice.java, rest-model/src/main/java/fi/otavanopisto/pyramus/rest/model/worklist/CourseBillingRestModel.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/CourseRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/util/PyramusConsts.java
- resolves #1501
- required by Muikku issue 6473
=> Endpoint for price of a paid assessment + minor usability fix to applications

rest/src/main/java/fi/otavanopisto/pyramus/rest/CourseRESTService.java
=> Assessment price hurdur fixes

pyramus/src/main/webapp/templates/users/edituser.jsp
=> Fixed dropdown visibility

rest/src/main/java/fi/otavanopisto/pyramus/rest/MuikkuRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/StudentRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/permissions/MuikkuPermissions.java
- ...and refactoring some deprecated methods while at it
=> Fix for some context reference warnings in server log

pyramus/src/main/java/fi/otavanopisto/pyramus/views/applications/MonthlySourceSummary.java, pyramus/src/main/webapp/scripts/gui/applications/application.js, pyramus/updates/123.001/231128-application-summary-recipients.xml
- resolves #1526
- ...and some miscellaneous application fixes
=> Configurable recipients for applications monthly summary

framework/src/main/java/fi/otavanopisto/pyramus/applications/ApplicationUtils.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/applications/AcceptApplicationViewController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/applications/ViewApplicationViewController.java
- fixes issues with application SSN validation
=> SSN hotfix

framework/src/main/java/fi/otavanopisto/pyramus/framework/StudyProgrammeProperties.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiConsts.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/base/StudyProgrammeDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/base/StudyProgramme.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/settings/SaveStudyProgrammesJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/settings/StudyProgrammesViewController.java, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/javascriptlocale.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/javascriptlocale_fi_FI.properties, pyramus/src/main/webapp/scripts/gui/settings/studyprogrammes.js, pyramus/updates/124.001/240122-studyprogramme-properties.xml, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/AssessmentController.java
=> StudyProgramme automatic subject selections

.github/workflows/deploy.yml
=> Deploy not necessary when pushing to master as it's already done probably

framework/src/main/java/fi/otavanopisto/pyramus/applications/ApplicationUtils.java
- fixes invalid birthday calculation based on SSN
=> Applications: Fix for invalid birthday calculation based on SSN

persistence/src/main/java/fi/otavanopisto/pyramus/dao/users/StaffMemberDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/TSB.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/users/StaffMember.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/users/SearchUsersJSONRequestController.java, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale_fi_FI.properties, pyramus/src/main/webapp/templates/users/searchusers.jsp, pyramus/src/main/webapp/templates/users/searchusersdialog.jsp
- Rajattu kurssin henkilökuntahaku vain aktiivisiin käyttäjiin
- Lisätty käyttäjähakuun käyttäjän aktiivisuusfiltteri
**Tarvitsee reindeksoinnin käyttäjähakua varten**
Closes #1551
=> Added activity filter to user search

pyramus/src/main/java/fi/otavanopisto/pyramus/json/users/CreateUserJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/users/CreateUserViewController.java, pyramus/src/main/webapp/templates/users/createuser.jsp
=> Poistettu tunnusten luominen kun opiskelijalle tehdään henkilökuntarooli

framework/src/main/java/fi/otavanopisto/pyramus/schedulers/PastStudentsCleanupScheduler.java
Adds batch size setting to the cleanup scheduler
=> Variable Cleanup batch size

framework/src/main/java/fi/otavanopisto/pyramus/security/impl/PyramusPermissionFeatures.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/students/StudentDAO.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/StudentRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/StudentController.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/permissions/AbstractPermissionFeature.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/permissions/AllowCourseTeacherPermissionFeature.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/permissions/StudentPermissions.java
Feature to allow Course Teachers to have access when they are a teacher of student (from ContextReference) on a course.
=> Course Teacher Feature

pyramus/src/main/java/fi/otavanopisto/pyramus/json/users/EditUserJSONRequestController.java
=> Allow removal of staff credentials

framework/src/main/java/fi/otavanopisto/pyramus/mailer/MailService.java, smvcj/src/main/java/fi/internetix/smvc/dispatcher/Servlet.java
=> Asynchronous mailing fix

framework/src/main/java/fi/otavanopisto/pyramus/applications/ApplicationUtils.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/applications/ViewApplicationViewController.java, pyramus/src/main/webapp/templates/applications/form-sections/application-form-section-internetix-school.jsp
=> Application OPS changes

rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/StudentController.java
=> Fix for incorrect grade date for linked assessments

persistence/src/main/java/fi/otavanopisto/pyramus/dao/application/ApplicationDAO.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/ArchiveLogEntryJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/SaveLogEntryJSONRequestController.java
- application removal threshold fix
=> Remove old applications based on last modified date rather than creation date

framework/src/main/java/fi/otavanopisto/pyramus/PyramusConsts.java, framework/src/main/java/fi/otavanopisto/pyramus/tor/StudentTOR.java, framework/src/main/java/fi/otavanopisto/pyramus/tor/StudentTORController.java, framework/src/main/java/fi/otavanopisto/pyramus/tor/TORSubject.java, framework/src/main/java/fi/otavanopisto/pyramus/tor/curriculum/TORCurriculum.java, framework/src/main/java/fi/otavanopisto/pyramus/tor/curriculum/TORCurriculumModule.java, framework/src/main/java/fi/otavanopisto/pyramus/tor/curriculum/TORCurriculumSubject.java, framework/src/main/resources/fi/otavanopisto/pyramus/tor/curriculum_2018.json, framework/src/main/resources/fi/otavanopisto/pyramus/tor/curriculum_2021.json, pyramus/src/main/java/fi/otavanopisto/pyramus/binary/ytl/YTLReportBinaryRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/ViewStudentViewController.java, pyramus/src/main/webapp/css/viewstudent-subjectcredits.css, pyramus/src/main/webapp/templates/students/viewstudent.jsp, rest/src/main/java/fi/otavanopisto/pyramus/rest/CourseRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/StudentRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/WorklistController.java
=> Indikaatio aineoppimäärän suorituksesta opiskelijan tietoihin

framework/src/main/java/fi/otavanopisto/pyramus/schedulers/PastStudentsCleanupScheduler.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/base/Person.java
=> Skip active persons at cleanup

.github/workflows/deploy.yml, .github/workflows/restTest.yml, .github/workflows/uiTests.yml, pom.xml, pyramus/pom.xml
- also uses java 17 for building, deploys etc.
Closes #1565
=> Necessary changes for running tests with java17

pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/UpdateApplicationStateJSONRequestController.java
=> Fix for not being able to return rejected applications back to processing

pyramus/src/main/webapp/templates/students/editstudent.jsp, pyramus/src/main/webapp/templates/students/viewstudent.jsp
=> Slice: Integraatiot-välilehden siirto

persistence/pom.xml, rest/src/main/java/fi/otavanopisto/pyramus/rest/MatriculationRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/ObjectFactory.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/MatriculationEligibilityController.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/permissions/MuikkuPermissions.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/util/PyramusRestUtils.java
Some code cleanup, no functional changes
* Moved two Matriculation methods to controller (needed later for Matriculation rework)
* Moved a Rest date utility method to PyramusRestUtils (needed later for Matriculation rework)
* Cleaned up unused imports
=> Code cleanup

rest-model/src/main/java/fi/otavanopisto/pyramus/rest/model/SliceStudentCardRestModel.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/SliceController.java
=> Added unique id to StudentCardRestModel

framework/src/main/java/fi/otavanopisto/pyramus/applications/ApplicationUtils.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/ArchiveApplicationJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/ArchiveStudentJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/EditStudentJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/applications/RemoveOldApplicationsScheduler.java
=> More application logging

framework/src/main/java/fi/otavanopisto/pyramus/framework/DateUtils.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/EditStudentViewController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/ViewStudentTools.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/ViewStudentValidationWarning.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/ViewStudentViewController.java, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale_fi_FI.properties, pyramus/src/main/webapp/css/theme.css, pyramus/src/main/webapp/templates/students/editstudent.jsp, pyramus/src/main/webapp/templates/students/viewstudent.jsp
=> Added Student StudyPeriod validation

framework/src/main/java/fi/otavanopisto/pyramus/framework/PyramusFileUtils.java, pyramus/src/test/java/fi/otavanopisto/pyramus/koski/AbstractKoskiTest.java, pyramus/src/test/java/fi/otavanopisto/pyramus/koski/KoskiJSONValidatorTestsIT.java, pyramus/src/test/java/fi/otavanopisto/pyramus/rest/AbstractRESTPermissionsTest.java, pyramus/src/test/java/fi/otavanopisto/pyramus/rest/MuikkuRestServicePermissionsTestsIT.java, pyramus/src/test/java/fi/otavanopisto/pyramus/ytl/YTLJSONTestsIT.java
Fixes warnings related to usage of deprecated methods
* Changed deprecated junit asserThat to hamcrest
* Changed deprecated isNumber to isCreatable
=> Minor code cleanup

pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale_fi_FI.properties, pyramus/src/main/webapp/templates/users/createuser.jsp, pyramus/src/main/webapp/templates/users/edituser.jsp
=> Käyttäjän koulutusohjelmalistan valinnat

pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/CreateStudentViewController.java
=> Study programme list in student creation

pyramus/src/test/java/fi/otavanopisto/pyramus/rest/AbstractRESTPermissionsTest.java, pyramus/src/test/java/fi/otavanopisto/pyramus/rest/AbstractRESTPermissionsTestJUnit5.java, pyramus/src/test/java/fi/otavanopisto/pyramus/rest/AbstractRESTServiceTest.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/JacksonConfigurator.java
This looks like a drop-in replacement but should still be tested a bit more.
=> Changed deprecated Jackson JSR310Module to JavaTimeModule

framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiScheduler.java
Fixes timers created with `ManagedScheduledExecutorService` lingering within container after undeploy. In hot deploy this caused multiple timers to be present, although the old ones didn't work and only spammed stack traces about missing CDI context instead. May also fix potential issues with container shutdown as the timer is now cancelled pre-stop.
=> Fixed KoskiScheduler on redeploy

rest/src/main/java/fi/otavanopisto/pyramus/rest/StudentRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/permissions/CourseAssessmentPermissions.java
=> Arviointipyynnön lukitus opinto-ohjaajille

pyramus/pom.xml
=> Bump mysqlConnector and mysql docker in tests to work with the bump

pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/ListCourseStudentVariablesJSONRequestController.java
Aiemmin, kun listattiin kuitattuja suorituksia, listautui myös kuittaamattomat suoritukset. Muutettu niin, että jos halutaan listata kuitattuja suorituksia, listataan vain kuitattuja suorituksia.
HD: 926339
=> Muutettu aineopintosuoritusten listaustapaa

pyramus/src/main/webapp/templates/applications/index.jsp
=> * Accessibility statement update

rest/src/main/java/fi/otavanopisto/pyramus/rest/MatriculationRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/StudentController.java
https://github.com/otavanopisto/muikku/issues/7164
=> Matriculation permissions for study guider

framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiConsts.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiController.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiSettings.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiStartupInitializer.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/ViewStudentViewController.java, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale_fi_FI.properties, pyramus/src/main/webapp/css/theme.css, pyramus/src/main/webapp/templates/students/viewstudent.jsp, pyramus/updates/136.001/241210_koski_var_usereditable.xml
Muutettu Kosken OID-kentät ei-muokattaviksi, siirretty niitä opiskelijan tiedoissa hieman eri paikkaan ja lisätty henkilön OID:sta linkki suoraan Koskeen opiskelijan profiiliin.
Closes #1589
=> Koski OID opiskelijan tiedoissa

framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiClient.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiController.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiStudentHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiStudentId.java, persistence/pom.xml, persistence/src/main/java/fi/otavanopisto/pyramus/dao/base/PersonDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/base/Person.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/base/search/PersonKoskiPersonOIDFieldIndexer.java, persistence/src/main/java/fi/otavanopisto/pyramus/domainmodel/base/search/PersonKoskiStudentOIDFieldIndexer.java
- Lisätty hakeminen Koski-OID:lla
- Korjattu hakeminen sähköpostilla
Closes #1236
=> Käyttäjähaun parannuksia

pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/EditStudentJSONRequestController.java
=> Opiskelijakortin päättymispäivä

rest/src/main/java/fi/otavanopisto/pyramus/rest/MuikkuRESTService.java
=> Study activity to return course data based on student's OPS

persistence/src/main/java/fi/otavanopisto/pyramus/dao/matriculation/MatriculationExamAttendanceDAO.java, persistence/src/main/java/fi/otavanopisto/pyramus/dao/matriculation/MatriculationExamEnrollmentDAO.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/matriculation/BrowseMatriculationExamsViewController.java, pyramus/src/main/webapp/templates/matriculation/management-browse-exams.jsp
Lisätty sarakkeet
* Lukumäärä vahvistetuista/peruutetuista/kaikista ilmoittautumislomakkeista
* Koe-ilmoittautumisien lukumäärä vahvistetuilla lomakkeilla
=> Lisätty pari summasaraketta yo-kirjoitusten kokeiden hallinnointiin

pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/EditStudentJSONRequestController.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/MuikkuRESTService.java
- resolves #1646
- student card activation bonus fix
=> Fix for study activity grades and student card activation

rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/permissions/CourseAssessmentPermissions.java
- resolves #1658
- fixes otavanopisto/muikku#7327
=> Added system access for listing course assessment requests

framework/src/main/java/fi/otavanopisto/pyramus/applications/ApplicationUtils.java, pyramus/src/main/webapp/templates/applications/form-sections/application-form-section-source.jsp
=> Hakemusten sanamuutoksia

common/src/main/java/fi/otavanopisto/pyramus/matriculation/MatriculationExamSubject.java, framework/src/main/resources/fi/otavanopisto/pyramus/ytl/ytl_ainekoodit.json, pyramus/src/main/java/fi/otavanopisto/pyramus/binary/ytl/YTLReportBinaryRequestController.java, pyramus/src/main/webapp/templates/matriculation/management-edit-enrollment.jsp, pyramus/src/main/webapp/templates/matriculation/matriculation-edit-grades.jsp
=> Lisätty saame äidinkielenä -valinnat yo-ilmoittautumiseen

framework/src/main/java/fi/otavanopisto/pyramus/applications/ApplicationMailErrorHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/applications/ApplicationUtils.java, framework/src/main/java/fi/otavanopisto/pyramus/mailer/MailErrorHandler.java, framework/src/main/java/fi/otavanopisto/pyramus/mailer/MailEvent.java, framework/src/main/java/fi/otavanopisto/pyramus/mailer/MailService.java, framework/src/main/java/fi/otavanopisto/pyramus/mailer/Mailer.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/SendMailJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/applications/UpdateApplicationStateJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/studentparents/EditStudentParentInvitationJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/applications/MonthlySourceSummary.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/ApplicationRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/StudentParentController.java
=> Hakemushistoriaan merkintä epäonnistuneesta postittelusta

persistence/src/main/java/fi/otavanopisto/pyramus/dao/students/StudentGroupStudentDAO.java, pyramus/src/main/java/fi/otavanopisto/pyramus/json/students/ArchiveStudentJSONRequestController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/EditStudentGroupViewController.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/ViewStudentGroupViewController.java
=> Student group views show archived students

pyramus/src/main/java/fi/otavanopisto/pyramus/views/students/ViewStudentViewController.java, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale.properties, pyramus/src/main/resources/fi/otavanopisto/pyramus/I18N/pyramuslocale_fi_FI.properties, pyramus/src/main/webapp/templates/students/viewstudent.jsp
Review: Hide whitespace
Closes #1684
=> Show matriculation tab for other curriculum students too

framework/src/main/java/fi/otavanopisto/pyramus/applications/ApplicationUtils.java, pyramus/src/main/java/fi/otavanopisto/pyramus/views/applications/ViewApplicationViewController.java
=> Aineopiskelijaksi hakevien ikärajamuutos

pyramus/src/main/java/fi/otavanopisto/pyramus/views/matriculation/BrowseMatriculationExamsViewController.java, pyramus/src/main/webapp/templates/matriculation/management-browse-exams.jsp
=> Yo-ilmoittautuminen: täytetty opiskelijan puolesta

pyramus/updates/143.001/251002-evaluation-prices.xml, rest-model/src/main/java/fi/otavanopisto/pyramus/rest/model/worklist/CourseBillingRestModel.java, rest-model/src/main/java/fi/otavanopisto/pyramus/rest/model/worklist/WorklistCoursePrice.java, rest-model/src/main/java/fi/otavanopisto/pyramus/rest/model/worklist/WorklistCoursePricesRestModel.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/StudentRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/WorklistRESTService.java, rest/src/main/java/fi/otavanopisto/pyramus/rest/controller/WorklistController.java
- support for exact evaluation pricing
=> Evaluation price overhaul

framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiEventListeners.java
=> Lisätty opiskelija Koski-päivitysjonoon opiskelijan luonnin yhteydessä
